# Recettes : Phénomènes Naturels, Cosmos, Formations Naturelles
RECIPES = [
  # ===== Météo : chaud, froid, eau dans l'air =====
  ("Air+Glace", "Froid"), ("Air+Neige", "Froid"), ("Glace+Température", "Froid"), 
  ("Air+Lave", "Chaleur"), ("Air+Brasier", "Chaleur"), ("Feu+Température", "Chaleur"), ("Air+Infrarouge", "Chaleur"),
  ("Eau+Froid", "Glace"), ("Froid+Lac", "Glace"),
  ("Froid+Pluie", "Neige"), ("Froid+Nuage", "Neige"), ("Air+Eau+Froid", "Neige"),
  ("Eau+Nuage", "Pluie"), ("Nuage+Nuage", "Pluie"), ("Eau+Gravité+Nuage", "Pluie"),
  ("Vapeur+Vent", "Nuage"), ("Air+Brouillard", "Nuage"), ("Air+Chaleur+Eau", "Nuage"),
  ("Nuage+Terre", "Brouillard"), ("Froid+Vapeur", "Brouillard"), ("Froid+Nuage+Vallée", "Brouillard"),
  ("Froid+Lac+Nuit", "Brouillard"),
  ("Nuit+Vapeur", "Rosée"), ("Brouillard+Plante", "Rosée"), ("Eau+Herbe+Nuit", "Rosée"),
  ("Froid+Plante+Vapeur", "Rosée"),
  ("Froid+Rosée", "Givre"), ("Brouillard+Froid", "Givre"), ("Glace+Vapeur", "Givre"),
  ("Arbre+Brouillard+Froid", "Givre"),
  ("Glace+Pluie", "Grêle"), ("Froid+Orage", "Grêle"), ("Glace+Nuage+Vent", "Grêle"),
  ("Éclair+Pluie", "Orage"), ("Éclair+Nuage", "Orage"), ("Chaleur+Nuage+Pluie", "Orage"),
  ("Orage+Vent", "Tempête"), ("Bourrasque+Pluie", "Tempête"), ("Nuage+Pluie+Vent", "Tempête"),
  ("Vent+Vent", "Bourrasque"),
  ("Air+Mouvement", "Vent"), ("Air+Pression", "Vent"),
  ("Électricité+Nuage", "Éclair"), ("Électricité+Tempête", "Éclair"), ("Friction+Nuage", "Éclair"),
  ("Bourrasque+Tempête", "Tornade"), ("Chaleur+Froid+Vent", "Tornade"), ("Chaleur+Froid+Orage+Vent", "Tornade"),
  ("Océan+Tempête", "Ouragan"), ("Chaleur+Mer+Tempête", "Ouragan"), ("Chaleur+Océan+Vent", "Ouragan"),
  ("Chaleur+Nuage+Océan+Vent", "Ouragan"),
  ("Neige+Vent", "Blizzard"), ("Froid+Tempête", "Blizzard"), ("Bourrasque+Neige", "Blizzard"),
  ("Froid+Neige+Pôle+Vent", "Blizzard"),
  ("Pluie+Pluie", "Déluge"), ("Nuage+Orage+Pluie+Pluie", "Déluge"),
  ("Pluie+Soleil", "Arc-en-ciel"), ("Cascade+Soleil", "Arc-en-ciel"),
  ("Pluie+Spectre lumineux", "Arc-en-ciel"),
  ("Oxygène+Oxygène+Oxygène", "Ozone"), ("Oxygène+Ultraviolet", "Ozone"), ("Oxygène+Éclair", "Ozone"),

  # ===== Feu, énergie, lumière, son =====
  ("Feu+Feu", "Brasier"), ("Charbon+Feu", "Brasier"),
  ("Feu+Maison+Vent", "Incendie"), ("Brasier+Vent", "Incendie"), 
  ("Feu+Forêt", "Feu de forêt"), ("Forêt+Incendie", "Feu de forêt"), ("Forêt+Éclair", "Feu de forêt"),
  ("Chaleur+Forêt+Sécheresse", "Feu de forêt"),
  ("Feu+Poudre à canon", "Explosion"), ("Pression+Vapeur", "Explosion"),
  ("Lumière+Soleil", "Énergie"),
  ("Ampoule+Électricité", "Lumière"), ("Air+Soleil", "Lumière"),
  ("Arbre+Lumière", "Ombre"), ("Lumière+Pierre", "Ombre"), ("Lumière+Montagne", "Ombre"),
  ("Air+Onde", "Son"), ("Air+Explosion", "Son"),
  ("Grotte+Son", "Écho"), ("Montagne+Son", "Écho"), ("Canyon+Son", "Écho"), ("Falaise+Son", "Écho"),

  # ===== Temps, jour, nuit, saisons =====
  ("Soleil+Terre", "Jour"), ("Nuit+Temps", "Jour"),
  ("Jour+Temps", "Nuit"), ("Jour+Ombre", "Nuit"), ("Ombre+Planète Terre", "Nuit"),
  ("Jour+Nuit", "Temps"),
  ("Orbite+Planète Terre", "Saison"), ("Chaleur+Froid+Temps", "Saison"),
  ("Orbite+Planète Terre+Soleil+Temps", "Saison"),

  # ===== Eau en mouvement, catastrophes =====
  ("Mer+Vent", "Vague"), ("Océan+Vent", "Vague"),
  ("Lune+Océan", "Marée"), ("Lune+Mer", "Marée"), ("Gravité+Océan", "Marée"), 
  ("Gravité+Lune+Océan+Soleil", "Marée"),
  ("Chaleur+Source", "Geyser"), ("Magma+Source", "Geyser"),
  ("Pluie+Rivière", "Inondation"), ("Eau+Plaine", "Inondation"), ("Déluge+Terre", "Inondation"),
  ("Orage+Pluie+Rivière", "Inondation"),
  ("Chaleur+Terre", "Sécheresse"), ("Chaleur+Lac", "Sécheresse"), ("Chaleur+Plaine+Soleil", "Sécheresse"),
  ("Énergie+Terre", "Séisme"), ("Continent+Mouvement", "Séisme"), ("Onde+Terre", "Séisme"),
  ("Océan+Séisme", "Tsunami"), ("Mer+Séisme", "Tsunami"), ("Astéroïde+Océan", "Tsunami"),
  ("Explosion+Océan+Volcan", "Tsunami"), ("Continent+Océan+Séisme+Vague", "Tsunami"),
  ("Montagne+Neige", "Avalanche"), ("Neige+Séisme", "Avalanche"), 
  ("Boue+Montagne", "Glissement de terrain"), ("Colline+Pluie", "Glissement de terrain"),
  ("Colline+Séisme", "Glissement de terrain"),
  ("Eau+Pierre", "Érosion"), ("Pierre+Vent", "Érosion"), ("Eau+Froid+Pierre", "Érosion"),
  ("Montagne+Pluie+Temps", "Érosion"),

  # ===== Formations : eaux =====
  ("Eau+Eau salée", "Mer"), ("Lac+Sel", "Mer"),
  ("Mer+Mer", "Océan"),
  ("Eau+Vallée", "Lac"), ("Castor+Rivière", "Lac"), ("Barrage+Rivière", "Lac"), ("Cratère+Eau", "Lac"),
  ("Eau+Montagne", "Rivière"), ("Montagne+Pluie", "Rivière"), ("Chaleur+Glacier", "Rivière"),
  
  ("Eau+Colline", "Source"), ("Grotte+Rivière", "Source"),
  ("Montagne+Rivière", "Cascade"), ("Falaise+Rivière", "Cascade"), ("Eau+Falaise", "Cascade"),
  ("Mer+Rivière", "Delta"), ("Océan+Rivière", "Delta"), ("Boue+Mer+Rivière", "Delta"),
  ("Boue+Mer+Rivière+Sable", "Delta"),
  ("Lac+Plante", "Marais"), ("Boue+Lac", "Marais"),
  ("Désert+Source", "Oasis"), ("Désert+Lac", "Oasis"), ("Désert+Palmier", "Oasis"),

  # ===== Formations : reliefs =====
  ("Terre+Terre", "Colline"), ("Érosion+Montagne", "Colline"),
  ("Continent+Continent", "Montagne"), ("Colline+Colline", "Montagne"),
  ("Explosion+Montagne", "Volcan"), ("Magma+Pression", "Volcan"), ("Chaleur+Lave+Montagne+Pression", "Volcan"),
  ("Montagne+Montagne", "Vallée"), ("Érosion+Rivière", "Vallée"), ("Glacier+Érosion", "Vallée"),
  ("Désert+Rivière", "Canyon"), ("Érosion+Vallée", "Canyon"), ("Pierre+Rivière+Temps", "Canyon"),
  ("Désert+Érosion+Rivière+Temps", "Canyon"),
  ("Mer+Montagne", "Falaise"), ("Montagne+Vague", "Falaise"), ("Mer+Pierre+Vague", "Falaise"),
  ("Érosion+Falaise", "Grotte"), ("Calcaire+Eau", "Grotte"), ("Calcaire+Érosion", "Grotte"),
  ("Calcaire+Eau+Montagne+Temps", "Grotte"),
  ("Eau+Grotte", "Stalactite"), ("Calcaire+Grotte", "Stalactite"), 
  ("Calcaire+Eau+Grotte+Temps", "Stalactite"),
  ("Érosion+Colline", "Plaine"), ("Rivière+Terre", "Plaine"), ("Inondation+Rivière+Terre", "Plaine"),
  ("Mer+Montagne+Plaine", "Continent"),
  ("Mer+Volcan", "Île"), ("Lave+Océan+Temps", "Île"),

  # ===== Formations : côtes, glaces, pôles =====
  ("Mer+Sable", "Plage"), ("Océan+Sable", "Plage"), ("Sable+Vague", "Plage"),
  ("Glace+Montagne", "Glacier"), ("Montagne+Neige+Temps", "Glacier"),
  ("Froid+Neige+Temps+Vallée", "Glacier"),
  ("Froid+Océan", "Banquise"), ("Froid+Mer", "Banquise"), ("Glace+Océan", "Banquise"),
  ("Glacier+Mer", "Iceberg"), ("Glacier+Océan", "Iceberg"),
  ("Froid+Planète Terre", "Pôle"), ("Magnétisme+Planète Terre", "Pôle"), ("Continent+Glace", "Pôle"),
  ("Froid+Glace+Neige+Planète Terre", "Pôle"),
  ("Corail+Mer", "Récif"), ("Corail+Océan", "Récif"), ("Chaleur+Corail+Lumière+Mer", "Récif"),
  ("Île+Récif", "Atoll"), ("Corail+Île", "Atoll"), ("Océan+Récif+Volcan", "Atoll"),
  ("Corail+Île+Océan+Temps", "Atoll"),

  # ===== Formations : végétation, sols =====
  ("Arbre+Arbre", "Forêt"),
  ("Forêt+Pluie", "Jungle"), ("Chaleur+Forêt", "Jungle"), ("Arbre+Chaleur+Pluie", "Jungle"),
  ("Maison+Plante+Terre", "Jardin"), ("Fleur+Humain+Terre", "Jardin"),
  ("Plaine+Plante+Plante", "Prairie"), ("Herbe+Plaine", "Prairie"), ("Fleur+Plaine", "Prairie"),
  ("Fleur+Herbe+Terre", "Prairie"),
  ("Chaleur+Prairie", "Savane"), ("Prairie+Sécheresse", "Savane"), ("Arbre+Chaleur+Prairie", "Savane"),
  ("Froid+Plaine", "Toundra"), ("Froid+Prairie", "Toundra"), ("Lichen+Plaine", "Toundra"),
  ("Froid+Mousse+Plaine", "Toundra"),
  ("Sable+Sable", "Désert"), ("Chaleur+Sable", "Désert"), ("Sécheresse+Terre", "Désert"),
  ("Lombric+Terre", "Sol fertile"), ("Engrais+Terre", "Sol fertile"), ("Décomposition+Terre", "Sol fertile"),
  ("Cendre+Terre", "Sol fertile"), ("Décomposition+Feuille+Lombric+Terre", "Sol fertile"),
  ("Marais+Temps", "Tourbe"), ("Marais+Mousse", "Tourbe"), ("Décomposition+Marais", "Tourbe"),
  ("Décomposition+Marais+Mousse+Temps", "Tourbe"),
  ("Os+Pierre+Temps", "Fossile"), ("Dinosaure+Pierre", "Fossile"), ("Pierre+Temps+Vie", "Fossile"),
  ("Boue+Os+Pierre+Temps", "Fossile"),
  ("Planète+Vie", "Planète Terre"), ("Océan+Planète", "Planète Terre"),

  # ===== Cosmos : le ciel vu d'en bas =====
  ("Étoile+Nuit", "Espace"), ("Ciel+Vide", "Espace"),
  ("Lumière+Nuit", "Étoile"), ("Espace+Feu", "Étoile"),
  ("Étoile+Jour", "Soleil"), ("Étoile+Planète Terre", "Soleil"),
  ("Espace+Terre", "Planète"), ("Astéroïde+Astéroïde", "Planète"), ("Gravité+Poussière d'étoiles", "Planète"),
  ("Astéroïde+Gravité+Poussière+Temps", "Planète"),
  ("Espace+Pierre", "Astéroïde"),
  ("Air+Astéroïde", "Météore"), ("Astéroïde+Planète Terre", "Météore"), ("Air+Comète", "Météore"),
  ("Météore+Terre", "Cratère"), ("Astéroïde+Lune", "Cratère"), 
  ("Météore+Lune", "Cratère"),
  ("Espace+Glace", "Comète"), ("Astéroïde+Glace", "Comète"), ("Astéroïde+Espace+Glace+Poussière", "Comète"),
  ("Planète+Soleil", "Orbite"), ("Gravité+Mouvement", "Orbite"), 
  ("Orbite+Planète", "Lune"), ("Astéroïde+Orbite", "Lune"), ("Orbite+Planète Terre+Pierre", "Lune"),
  ("Explosion+Orbite+Planète+Planète Terre", "Lune"),
  ("Lune+Soleil", "Éclipse"), ("Ombre+Soleil", "Éclipse"), ("Lune+Ombre+Planète Terre", "Éclipse"),
  ("Lune+Ombre+Planète Terre+Soleil", "Éclipse"),
  ("Lune+Marée", "Marée lunaire"),
  ("Lumière+Pôle", "Aurore"), ("Plasma+Pôle", "Aurore"), ("Magnétisme+Pôle+Soleil", "Aurore"),
  ("Lumière+Magnétisme+Plasma+Pôle", "Aurore"),
  ("Étoile+Étoile", "Constellation"), ("Étoile+Mythe", "Constellation"),
  ("Étoile+Humain+Nuit", "Constellation"), ("Étoile+Étoile+Mythe+Nuit", "Constellation"),

  # ===== Cosmos : système solaire =====
  ("Orbite+Soleil", "Système solaire"), ("Planète+Planète+Soleil", "Système solaire"),
  ("Mars+Planète Terre+Soleil", "Système solaire"), ("Jupiter+Mars+Saturne+Soleil", "Système solaire"),
  ("Planète+Rouille", "Mars"), ("Désert+Planète", "Mars"),
  ("Gaz+Planète", "Jupiter"), ("Hydrogène+Planète", "Jupiter"), ("Planète+Tempête", "Jupiter"),
  ("Glace+Orbite", "Anneaux planétaires"), ("Orbite+Poussière", "Anneaux planétaires"),
  
  ("Anneaux planétaires+Planète", "Saturne"),
  ("Anneaux planétaires+Gaz+Planète", "Saturne"),

  # ===== Cosmos savant : étoiles, galaxies, univers =====
  ("Gravité+Hydrogène", "Étoile"), ("Gravité+Nébuleuse", "Étoile"), ("Fusion nucléaire+Gravité", "Étoile"),
  ("Espace+Nuage", "Nébuleuse"), ("Espace+Poussière", "Nébuleuse"), ("Espace+Gaz", "Nébuleuse"),
  ("Espace+Hydrogène", "Nébuleuse"), ("Espace+Gaz+Hydrogène+Poussière", "Nébuleuse"),
  ("Étoile+Poussière", "Poussière d'étoiles"), ("Poussière+Supernova", "Poussière d'étoiles"),
  ("Étoile+Explosion", "Supernova"), ("Étoile+Masse+Temps", "Supernova"),
  ("Étoile+Explosion+Gravité+Masse", "Supernova"),
  ("Gravité+Supernova", "Trou noir"),
  ("Étoile+Gravité+Masse+Temps", "Trou noir"),
  ("Neutron+Étoile", "Pulsar"), ("Magnétisme+Supernova", "Pulsar"),
  ("Galaxie+Trou noir", "Quasar"), ("Énergie+Trou noir", "Quasar"), ("Radiation+Trou noir", "Quasar"),
  ("Énergie+Galaxie+Lumière+Trou noir", "Quasar"),
  ("Étoile+Étoile+Étoile", "Galaxie"), ("Étoile+Matière noire", "Galaxie"),
  ("Étoile+Étoile+Gravité+Nébuleuse", "Galaxie"),
  ("Galaxie+Système solaire", "Voie lactée"), ("Galaxie+Planète Terre", "Voie lactée"),
  ("Étoile+Galaxie+Nuit+Planète Terre", "Voie lactée"),
  ("Galaxie+Gravité", "Matière noire"),
  ("Espace+Explosion+Temps", "Big Bang"),
  ("Chaleur+Énergie+Espace+Temps", "Big Bang"),
  ("Big Bang+Temps", "Univers"), ("Galaxie+Galaxie", "Univers"), ("Espace+Galaxie", "Univers"),
  ("Espace+Galaxie+Matière noire+Temps", "Univers"),
  # ===== Chemins supplémentaires =====
  ("Lune+Planète Terre", "Orbite"), ("Friction+Mouvement", "Chaleur"), ("Glace+Vent", "Froid"),
  ("Mur+Son", "Écho"),
  ("Eau+Glacier+Vallée", "Lac"), ("Arbre+Plante+Pluie", "Forêt"), ("Eau+Eau+Eau", "Océan"),
  ("Chaleur+Étoile+Lumière", "Soleil"), ("Espace+Gravité+Pierre", "Planète"), ("Espace+Glace+Poussière", "Comète"),
  ("Espace+Feu+Pierre", "Météore"),
  ("Continent+Continent+Mouvement", "Séisme"), ("Boue+Colline+Pluie", "Glissement de terrain"),
  ("Air+Chaleur+Froid", "Vent"), ("Arbre+Feuille+Temps", "Saison"), ("Glacier+Montagne+Temps", "Vallée"),
  ("Glace+Mer+Pôle", "Banquise"), ("Feu+Gaz+Pression", "Explosion"), ("Bois+Feu+Vent", "Brasier"),
  ("Fer+Oxydation+Planète", "Mars"),
]
