# Recettes : Flore, Biologie, Vie et Créatures
RECIPES = [
  # ===================== FLORE =====================
  # Plante / Arbre / Bois (chemins supplémentaires)
  ("Graine+Terre", "Plante"),
  ("Eau+Graine", "Plante"),
  ("Graine+Sol fertile", "Plante"),
  ("Eau+Graine+Terre", "Plante"),
  ("Eau+Graine+Soleil+Terre", "Plante"),
  ("Feuille+Fleur+Racine+Graine", "Plante"),
  ("Graine+Temps", "Arbre"),
  ("Bois+Racine", "Arbre"),
  ("Arbre+Hache", "Bois"),
  # Herbe
  ("Plante+Pluie", "Herbe"),
  # Fleur
  ("Jardin+Plante", "Fleur"),
  # Rose
  ("Fleur+Jardin", "Rose"),
  ("Amour+Fleur", "Rose"),
  # Cactus
  ("Désert+Plante", "Cactus"),
  ("Plante+Sable", "Cactus"),
  ("Désert+Eau+Plante", "Cactus"),
  # Bambou
  ("Arbre+Herbe", "Bambou"),
  ("Herbe+Jungle", "Bambou"),
  # Blé
  ("Herbe+Humain", "Blé"),
  ("Champ+Herbe", "Blé"),
  ("Champ+Graine+Soleil", "Blé"),
  # Riz
  ("Herbe+Marais", "Riz"),
  ("Blé+Marais", "Riz"),
  ("Champ+Eau+Herbe", "Riz"),
  # Maïs
  # Lierre
  ("Château+Plante", "Lierre"),
  ("Mur+Plante", "Lierre"),
  # Vigne / Raisin
  ("Colline+Plante", "Vigne"),
  ("Fruit+Vigne", "Raisin"),
  ("Soleil+Vigne", "Raisin"),
  # Fruit / Pomme / Olive
  ("Arbre+Fleur", "Fruit"),
  ("Fleur+Pollinisation", "Fruit"),
  ("Arbre+Fruit", "Pomme"),
  ("Fruit+Gravité", "Pomme"),
  ("Fruit+Huile", "Olive"),
  ("Arbre+Fruit+Soleil", "Olive"),
  # Racine / Légume / Pomme de terre
  ("Arbre+Terre", "Racine"),
  ("Boue+Plante", "Racine"),
  ("Jardin+Racine", "Légume"),
  ("Agriculture+Plante", "Légume"),
  ("Légume+Terre", "Pomme de terre"),
  # Tournesol
  ("Fleur+Lumière", "Tournesol"),
  ("Fleur+Soleil", "Tournesol"),
  ("Fleur+Graine+Soleil", "Tournesol"),
  # Chêne / Sapin / Palmier
  ("Arbre+Temps", "Chêne"),
  ("Arbre+Force", "Chêne"),
  ("Arbre+Neige", "Sapin"),
  ("Arbre+Montagne", "Sapin"),
  ("Arbre+Oasis", "Palmier"),
  ("Arbre+Île", "Palmier"),
  # Mousse / Fougère / Lichen
  ("Pierre+Plante", "Mousse"),
  ("Ombre+Plante", "Mousse"),
  ("Forêt+Plante", "Fougère"),
  ("Plante+Préhistoire", "Fougère"),
  ("Ombre+Forêt+Plante", "Fougère"),
  ("Algue+Champignon", "Lichen"),
  ("Pierre+Symbiose", "Lichen"),
  ("Algue+Champignon+Pierre", "Lichen"),
  # Champignon
  ("Bois+Pluie", "Champignon"),
  ("Décomposition+Forêt", "Champignon"),
  # Algue / Nénuphar
  ("Eau+Plante", "Algue"),
  ("Océan+Plante", "Algue"),
  ("Fleur+Lac", "Nénuphar"),
  ("Fleur+Marais", "Nénuphar"),
  # Graine / Pollen / Feuille
  ("Fleur+Pollen", "Graine"),
  ("Plante+Temps", "Graine"),
  ("Fleur+Vent", "Pollen"),
  ("Fleur+Poussière", "Pollen"),
  ("Abeille+Fleur+Poussière", "Pollen"),
  ("Arbre+Vent", "Feuille"),
  ("Arbre+Saison", "Feuille"),
  ("Chlorophylle+Plante", "Feuille"),
  # Plantes cultivées
  ("Coton+Plante", "Cotonnier"),
  ("Champ+Nuage+Plante", "Cotonnier"),
  ("Fleur+Herbe+Humain", "Lin"),
  ("Plante+Tissu", "Lin"),
  ("Champ+Fleur+Herbe", "Lin"),
  ("Feuille+Vapeur", "Thé"),
  ("Eau+Feu+Feuille", "Thé"),
  ("Eau+Feu+Graine", "Café"),
  ("Fruit+Jungle", "Cacao"),
  ("Arbre+Graine+Jungle", "Cacao"),
  ("Bambou+Sucre", "Canne à sucre"),
  ("Herbe+Sucre", "Canne à sucre"),
  ("Herbe+Sorcier", "Herbe médicinale"),
  ("Herbe+Santé", "Herbe médicinale"),
  ("Herbe+Maladie", "Herbe médicinale"),

  # ===================== BIOLOGIE =====================
  # Vie (chimie prébiotique, expérience de Miller-Urey)
  ("Ammoniac+Eau+Éclair+Méthane", "Vie"),
  ("Molécule+Océan+Éclair", "Vie"),
  # Cellule / Organisme
  ("Molécule+Vie", "Cellule"),
  ("Microscope+Vie", "Cellule"),
  ("Océan+Vie+Éclair", "Cellule"),
  ("Cellule+Cellule", "Organisme"),
  ("Cellule+Vie", "Organisme"),
  ("Cellule+Cellule+Cellule", "Organisme"),
  # ADN / Gène / Protéine / Enzyme
  ("Cellule+Molécule", "ADN"),
  ("Azote+Phosphore+Sucre", "ADN"),
  ("ADN+Reproduction", "Gène"),
  ("ADN+Famille", "Gène"),
  ("Cellule+Gène", "Protéine"),
  ("Azote+Carbone+Molécule", "Protéine"),
  ("Azote+Carbone+Hydrogène+Oxygène", "Protéine"),
  ("Catalyseur+Protéine", "Enzyme"),
  ("Levure+Protéine", "Enzyme"),
  # Microbes
  ("Bactérie+Microscope", "Microbe"),
  ("Eau+Microscope", "Microbe"),
  ("Boue+Cellule", "Bactérie"),
  ("Lait+Microbe", "Bactérie"),
  ("ADN+Protéine", "Virus"),
  ("Cellule+Parasite", "Virus"),
  ("Microbe+Océan", "Plancton"),
  ("Algue+Microbe", "Plancton"),
  ("Champignon+Microbe", "Levure"),
  ("Cellule+Champignon", "Levure"),
  # Photosynthèse / Chlorophylle / Respiration
  ("Feuille+Molécule", "Chlorophylle"),
  ("Cellule+Feuille", "Chlorophylle"),
  ("Chlorophylle+Lumière", "Photosynthèse"),
  ("Plante+Soleil", "Photosynthèse"),
  ("Dioxyde de carbone+Eau+Lumière", "Photosynthèse"),
  ("Chlorophylle+Dioxyde de carbone+Eau+Lumière", "Photosynthèse"),
  ("Air+Organisme", "Respiration"),
  ("Organisme+Oxygène", "Respiration"),
  ("Cellule+Oxygène+Sucre", "Respiration"),
  # Fermentation / Décomposition
  ("Fruit+Levure", "Fermentation"),
  ("Bactérie+Lait+Temps", "Fermentation"),
  ("Feuille+Lombric", "Décomposition"),
  ("Bactérie+Mort", "Décomposition"),
  ("Bois+Champignon", "Décomposition"),
  ("Bactérie+Organisme+Temps", "Décomposition"),
  # Reproduction / Œuf / Embryon / Métamorphose
  ("Vie+Vie", "Reproduction"),
  ("Organisme+Organisme", "Reproduction"),
  ("Nid+Oiseau", "Œuf"),
  ("Nid+Poule", "Œuf"),
  ("Oiseau+Reproduction", "Œuf"),
  ("Poisson+Reproduction", "Œuf"),
  ("Cellule+Reproduction", "Embryon"),
  ("Vie+Œuf", "Embryon"),
  ("Cellule+Cellule+Cellule+Cellule", "Embryon"),
  ("Chenille+Temps", "Métamorphose"),
  ("Asticot+Temps", "Métamorphose"),
  ("Chenille+Papillon+Temps", "Métamorphose"),
  # Espèce / Évolution / Mutation / Extinction
  ("Organisme+Reproduction", "Espèce"),
  ("Organisme+Évolution", "Espèce"),
  ("Gène+Organisme+Reproduction", "Espèce"),
  ("Poisson+Temps+Terre", "Évolution"),
  ("Mutation+Temps", "Évolution"),
  ("Espèce+Fossile", "Évolution"),
  ("Espèce+Mutation+Reproduction+Temps", "Évolution"),
  ("ADN+Radiation", "Mutation"),
  ("Gène+Radiation", "Mutation"),
  ("ADN+Ultraviolet", "Mutation"),
  ("ADN+Fumée", "Mutation"),
  ("Dinosaure+Météore", "Extinction"),
  ("Astéroïde+Dinosaure", "Extinction"),
  ("Espèce+Mort", "Extinction"),
  ("Chasse+Mammouth", "Extinction"),
  # Symbiose / Pollinisation / Parasite
  ("Champignon+Racine", "Symbiose"),
  ("Algue+Corail", "Symbiose"),
  ("Bactérie+Organisme", "Symbiose"),
  ("Fleur+Papillon", "Pollinisation"),
  ("Pollen+Vent", "Pollinisation"),
  ("Insecte+Pollen", "Pollinisation"),
  ("Chauve-souris+Fleur", "Pollinisation"),
  ("Organisme+Sang+Insecte", "Parasite"),
  # Instinct
  ("Araignée+Toile d'araignée", "Instinct"),
  ("Gène+Mémoire", "Instinct"),
  ("Peur+Vie", "Instinct"),
  # Écologie
  ("Chenille+Oiseau+Plante", "Chaîne alimentaire"),
  ("Herbe+Loup+Mouton", "Chaîne alimentaire"),
  ("Plancton+Poisson+Requin", "Chaîne alimentaire"),
  ("Faim+Organisme", "Chaîne alimentaire"),
  ("Chaîne alimentaire+Forêt", "Écosystème"),
  ("Chaîne alimentaire+Océan", "Écosystème"),
  ("Récif+Symbiose", "Écosystème"),
  ("Bactérie+Mammifère+Plante+Soleil", "Écosystème"),
  ("Espèce+Espèce", "Biodiversité"),
  ("Espèce+Écosystème", "Biodiversité"),
  ("Insecte+Mammifère+Oiseau+Plante", "Biodiversité"),

  # ===================== VIE ET CRÉATURES =====================
  # Chemins supplémentaires pour les créatures de base
  ("Rivière+Vie", "Poisson"),
  ("Dinosaure+Plume", "Oiseau"),
  ("Plume+Vie", "Oiseau"),
  ("Air+Dinosaure+Plume", "Oiseau"),
  ("Œuf+Papillon", "Chenille"),
  ("Chenille+Métamorphose", "Papillon"),
  ("Insecte+Lumière", "Luciole"),
  ("Air+Préhistoire", "Ptérodactyle"),
  ("Insecte+Viande", "Asticot"),
  ("Décomposition+Insecte", "Asticot"),
  ("Organisme+Sol fertile", "Lombric"),
  ("Corail+Poisson", "Poisson Tropical"),
  ("Poisson+Récif", "Poisson Tropical"),
  ("Banquise+Poisson", "Poisson Polaire"),
  ("Oiseau+Poisson", "Poisson Volant"),
  ("Pression+Poisson", "Poisson Abyssal"),
  ("Nuit+Océan+Poisson", "Poisson Abyssal"),
  # Insectes et petites bêtes
  ("Asticot+Métamorphose", "Insecte"),
  ("Fleur+Insecte", "Abeille"),
  ("Insecte+Miel", "Abeille"),
  ("Insecte+Terre", "Fourmi"),
  ("Force+Insecte", "Fourmi"),
  ("Soie+Chasse", "Araignée"),  # la chasseresse qui tisse sa soie (l'araignée n'est pas un insecte : huit pattes, c'est un arachnide)
  ("Araignée+Insecte", "Toile d'araignée"),
  ("Araignée+Tissu", "Toile d'araignée"),
  ("Jardin+Pluie", "Escargot"),  # il sort au jardin après la pluie (l'escargot n'est pas un ver : c'est un mollusque)
  ("Insecte+Marais", "Moustique"),
  ("Insecte+Sang", "Moustique"),
  ("Insecte+Maladie", "Moustique"),
  ("Abeille+Arbre", "Ruche"),
  ("Abeille+Maison", "Ruche"),
  ("Abeille+Cire+Miel", "Ruche"),
  # Amphibiens et reptiles
  ("Évolution+Poisson", "Grenouille"),
  ("Eau+Métamorphose", "Grenouille"),
  ("Eau+Poisson+Temps+Terre", "Grenouille"),
  ("Salamandre+Écaille", "Lézard"),
  ("Salamandre+Soleil", "Lézard"),
  ("Outil+Poisson", "Écaille"),
  ("Évolution+Lézard", "Serpent"),
  ("Plage+Œuf", "Tortue"),  # la tortue marine éclot dans le sable de la plage (la tortue n'est pas un lézard)
  ("Armure+Écaille", "Tortue"),  # le reptile en armure : sa carapace est couverte d'écailles
  ("Marais+Écaille", "Crocodile"),  # une bête à écailles des marais (le crocodile n'est pas un lézard, il est cousin des oiseaux et des dinosaures)
  ("Écaille+Préhistoire", "Dinosaure"),
  ("Fossile+Os", "Dinosaure"),
  # Oiseaux
  ("Oiseau+Vent", "Plume"),
  ("Arbre+Oiseau", "Nid"),
  ("Herbe+Oiseau", "Nid"),
  ("Bois+Oiseau+Œuf", "Nid"),
  ("Montagne+Oiseau", "Aigle"),
  ("Force+Oiseau", "Aigle"),
  ("Oiseau+Souris", "Hibou"),
  ("Nuit+Oiseau", "Hibou"),
  ("Oiseau+Sagesse", "Hibou"),
  ("Glace+Oiseau", "Manchot"),  # les manchots vivent dans l'hémisphère sud, sur les glaces antarctiques
  ("Banquise+Oiseau", "Manchot"),  # le manchot empereur se reproduit sur la banquise
  ("Iceberg+Oiseau", "Manchot"),  # l'image des manchots Adélie posés sur un iceberg
  ("Glace+Océan+Oiseau", "Manchot"),
  ("Froid+Oiseau marin", "Pingouin"),  # le pingouin torda, oiseau marin des mers froides de l'Atlantique nord
  ("Graine+Oiseau", "Poule"),
  ("Oiseau+Élevage", "Poule"),
  ("Oiseau+Océan", "Oiseau marin"),
  ("Mer+Oiseau", "Oiseau marin"),
  ("Lac+Oiseau", "Cygne"),
  ("Amour+Oiseau", "Cygne"),
  # Mammifères
  ("Lait+Vie", "Mammifère"),
  ("Chaleur+Naissance+Évolution", "Mammifère"),
  ("Fourrure+Vie", "Mammifère"),
  ("Mammifère+Neige", "Fourrure"),
  ("Froid+Mammifère", "Fourrure"),
  ("Blé+Mammifère", "Souris"),
  ("Fromage+Mammifère", "Souris"),
  ("Mammifère+Souris", "Chat"),
  ("Maison+Souris+Mammifère", "Chat"),
  ("Loup+Os", "Chien"),
  ("Loup+Maison", "Chien"),
  ("Humain+Loup+Os", "Chien"),
  ("Forêt+Mammifère", "Loup"),
  ("Chevalier+Mammifère", "Cheval"),
  ("Mammifère+Prairie", "Cheval"),
  ("Mammifère+Plaine", "Cheval"),
  ("Herbe+Mammifère", "Vache"),
  ("Lait+Mammifère", "Vache"),
  ("Herbe+Lait+Mammifère", "Vache"),
  ("Laine+Mammifère", "Mouton"),
  ("Boue+Mammifère", "Cochon"),
  ("Champignon+Mammifère", "Cochon"),
  ("Mammifère+Miel", "Ours"),
  ("Mammifère+Ruche", "Ours"),
  ("Grotte+Mammifère", "Ours"),
  ("Glace+Ours", "Ours polaire"),
  ("Banquise+Ours", "Ours polaire"),
  ("Mammifère+Océan", "Baleine"),
  ("Mammifère+Plancton", "Baleine"),
  ("Mammifère+Océan+Temps", "Baleine"),
  ("Mammifère+Vague", "Dauphin"),
  ("Poisson+Sang", "Requin"),
  ("Encre+Océan", "Pieuvre"),
  ("Araignée+Océan", "Crabe"),  # l'« araignée de mer » est un crabe
  ("Plage+Vie", "Crabe"),
  ("Calcaire+Océan", "Corail"),
  ("Air+Vie+Écho", "Chauve-souris"),
  ("Mammifère+Écho", "Chauve-souris"),
  ("Mammifère+Nuit+Air", "Chauve-souris"),
  ("Arbre+Mammifère", "Singe"),
  ("Jungle+Mammifère", "Singe"),
  ("Arbre+Fruit+Mammifère", "Singe"),
  ("Glace+Mammifère", "Mammouth"),
  ("Glace+Éléphant", "Mammouth"),
  ("Fourrure+Glace+Mammifère", "Mammouth"),
  ("Mammifère+Mémoire", "Éléphant"),
  ("Géant+Mammifère+Savane", "Éléphant"),  # le géant de la savane : le plus grand animal terrestre
  ("Mammifère+Savane", "Lion"),
  ("Mammifère+Roi", "Lion"),
  ("Désert+Mammifère", "Chameau"),
  ("Désert+Eau+Mammifère", "Chameau"),
  ("Bois+Mammifère", "Castor"),
  ("Mammifère+Rivière", "Castor"),
  ("Barrage+Mammifère", "Castor"),
  ("Bois+Eau+Mammifère", "Castor"),
  ("Décomposition+Mammifère", "Os"),
  ("Calcium+Organisme", "Os"),
  ("Mort+Mammifère+Temps", "Os"),

  # ---- chemins complémentaires (3 et 4 ingrédients) ----
  ("Plante+Pluie+Terre", "Herbe"),
  ("Jardin+Lumière+Plante", "Fleur"),
  ("Amour+Fleur+Jardin", "Rose"),
  ("Arbre+Herbe+Jungle", "Bambou"),
  ("Blé+Humain+Jungle", "Maïs"),
  ("Arbre+Plage+Soleil", "Palmier"),
  ("Arbre+Montagne+Neige", "Sapin"),
  ("Bois+Ombre+Pluie", "Champignon"),
  ("Eau+Fleur+Lac", "Nénuphar"),
  ("Herbe+Humain+Maladie", "Herbe médicinale"),
  ("Arbre+Saison+Vent", "Feuille"),
  ("Arbre+Eau+Terre", "Racine"),
  ("ADN+Cellule+Reproduction", "Gène"),
  ("Cellule+Gène+Parasite", "Virus"),
  ("Algue+Microbe+Océan", "Plancton"),
  ("Champignon+Microbe+Sucre", "Levure"),
  ("Bactérie+Cellule+Temps", "Symbiose"),
  ("ADN+Radiation+Reproduction", "Mutation"),
  ("Chasse+Espèce+Humain", "Extinction"),
  ("Fleur+Insecte+Miel", "Abeille"),
  ("Feuille+Insecte+Terre", "Fourmi"),
  ("Insecte+Soie+Chasse", "Araignée"),  # elle chasse les insectes avec sa soie
  ("Jardin+Pluie+Vie", "Escargot"),
  ("Insecte+Marais+Sang", "Moustique"),
  ("Montagne+Oiseau+Vent", "Aigle"),
  ("Nuit+Oiseau+Souris", "Hibou"),
  ("Ferme+Graine+Oiseau", "Poule"),
  ("Amour+Lac+Oiseau", "Cygne"),
  ("Blé+Maison+Mammifère", "Souris"),
  ("Herbe+Mammifère+Plaine", "Cheval"),
  ("Fourrure+Herbe+Montagne", "Mouton"),
  ("Boue+Ferme+Mammifère", "Cochon"),
  ("Grotte+Mammifère+Miel", "Ours"),
  ("Cerveau+Mammifère+Océan", "Dauphin"),
  ("Chasse+Océan+Poisson", "Requin"),
  ("Encre+Escargot+Méduse", "Pieuvre"),
  ("Araignée+Océan+Plage", "Crabe"),
  ("Mammifère+Roi+Savane", "Lion"),
  ("Froid+Mammifère+Neige", "Fourrure"),
  ("Pierre+Salamandre+Soleil", "Lézard"),
  ("Océan+Plancton+Vie", "Méduse"),
  ("Corail+Lumière+Poisson", "Poisson Tropical"),
  ("Champ+Eau+Herbe+Soleil", "Riz"),
  ("Champ+Graine+Pluie+Soleil", "Blé"),
  ("Champ+Fleur+Graine+Soleil", "Tournesol"),
  ("Colline+Fruit+Lierre+Soleil", "Vigne"),
  ("Arbre+Désert+Eau+Sable", "Palmier"),
  ("Arbre+Froid+Montagne+Neige", "Sapin"),
  ("Cellule+Cristal+Molécule+Rayons X", "ADN"),
  ("Bactérie+Bois+Champignon+Lombric", "Décomposition"),
  ("Fruit+Levure+Sucre+Temps", "Fermentation"),
  ("Chaleur+Nid+Temps+Œuf", "Oiseau"),
  ("Air+Chenille+Feuille+Temps", "Papillon"),
  ("Espèce+Temps+Écosystème+Évolution", "Biodiversité"),
  ("Dinosaure+Feu+Météore+Poussière", "Extinction"),
  ("Glace+Océan+Oiseau+Poisson", "Manchot"),
  ("Mammifère+Océan+Temps+Évolution", "Baleine"),
  ("Humain+Loup+Maison+Os", "Chien"),
  ("Ferme+Herbe+Lait+Mammifère", "Vache"),
  ("Herbe+Laine+Mammifère+Montagne", "Mouton"),
  ("Fourrure+Glace+Mammifère+Préhistoire", "Mammouth"),
  ("Abeille+Arbre+Cire+Miel", "Ruche"),
  ("Champignon+Feuille+Insecte+Terre", "Fourmi"),
  ("Bois+Eau+Mammifère+Rivière", "Castor"),
  ("Algue+Calcaire+Méduse+Récif", "Corail"),
  ("Herbe+Loup+Mouton+Soleil", "Chaîne alimentaire"),
  ("Grotte+Mammifère+Nuit+Écho", "Chauve-souris"),
  ("Nuit+Océan+Poisson+Pression", "Poisson Abyssal"),
  ("Arbre+Fruit+Graine+Jungle", "Cacao"),
]
