# Recettes : Corps et Esprit, Créations Humaines
RECIPES = [
  # ---------- Corps ----------
  ("Feu+Humain", "Douleur"), ("Cactus+Humain", "Douleur"), ("Humain+Lance", "Chasse"),
  ("Maladie+Muscle", "Douleur"),
  ("Douleur+Épée", "Sang"), ("Muscle+Épée", "Sang"), 
  ("Énergie+Humain", "Muscle"), ("Force+Humain", "Muscle"), ("Humain+Mouvement", "Muscle"),
  ("Muscle+Sang", "Cœur"), ("Humain+Sang", "Cœur"), 
  ("Mort+Temps", "Squelette"), ("Os+Os", "Squelette"), ("Humain+Os", "Squelette"),
  ("Temps+Tombe", "Squelette"),
  ("Humain+Lumière", "Œil"), ("Cellule+Lumière", "Œil"), ("Humain+Lentille", "Œil"),
  ("Éclair+Humain", "Neurone"), ("Cellule+Électricité", "Neurone"), ("Cellule+Pensée", "Neurone"),
  ("Neurone+Neurone", "Cerveau"), ("Neurone+Organisme", "Cerveau"), 
  ("Neurone+Neurone+Neurone+Neurone", "Cerveau"),
  ("Faim+Humain", "Chasse"),
  ("Humain+Sécheresse", "Faim"), ("Désert+Humain", "Faim"),
  
  # ---------- Esprit ----------
  ("Cerveau+Esprit", "Pensée"), ("Cerveau+Neurone", "Pensée"), ("Cerveau+Électricité", "Pensée"),
  
  ("Pensée+Temps", "Mémoire"), ("Cerveau+Temps", "Mémoire"), ("Neurone+Temps", "Mémoire"),
  ("Livre+Pensée", "Mémoire"),
  ("Humain+Nuit", "Sommeil"), ("Cerveau+Nuit", "Sommeil"), ("Enfant+Musique", "Sommeil"),
  ("Humain+Maison+Nuit", "Sommeil"),
  ("Pensée+Sommeil", "Rêve"), ("Esprit+Sommeil", "Rêve"),
  ("Nuit+Pensée", "Rêve"),
  ("Cœur+Esprit", "Émotion"), ("Cerveau+Cœur", "Émotion"), ("Cœur+Pensée", "Émotion"),
  ("Humain+Ombre", "Peur"), ("Nuit+Émotion", "Peur"), ("Mort+Émotion", "Peur"),
  ("Fantôme+Humain", "Peur"), ("Enfant+Nuit+Orage", "Peur"),
  ("Arc-en-ciel+Émotion", "Joie"), ("Musique+Émotion", "Joie"), ("Soleil+Émotion", "Joie"),
  ("Enfant+Jardin", "Joie"),
  ("Pluie+Émotion", "Tristesse"), ("Joie+Mort", "Tristesse"),
  ("Feu+Émotion", "Colère"), ("Tempête+Émotion", "Colère"),
  ("Guerre+Émotion", "Colère"),
  ("Cœur+Humain", "Amour"), ("Cœur+Cœur", "Amour"), ("Humain+Rose", "Amour"),
  
  ("Humain+Humain", "Famille"), ("Amour+Maison", "Famille"), ("Enfant+Maison", "Famille"),
  ("Enfant+Humain+Humain", "Famille"), ("Enfant+Humain+Humain+Maison", "Famille"),
  ("Famille+Vie", "Naissance"), ("Amour+Vie", "Naissance"), ("Embryon+Humain", "Naissance"),
  ("Humain+Reproduction", "Naissance"), ("Amour+Humain+Humain", "Naissance"),
  ("Amour+Humain+Humain+Temps", "Naissance"),
  ("Humain+Naissance", "Enfant"), ("Famille+Naissance", "Enfant"), ("Embryon+Temps", "Enfant"),
  ("Humain+Temps", "Vieillesse"), ("Horloge+Humain", "Vieillesse"),
  ("Humain+Marais", "Maladie"), ("Humain+Virus", "Maladie"), ("Bactérie+Humain", "Maladie"),
  ("Humain+Moustique", "Maladie"), 
  ("Maladie+Plante", "Remède"), ("Herbe médicinale+Maladie", "Remède"), ("Maladie+Potion", "Remède"),
  ("Eau+Herbe médicinale+Feu", "Remède"),
  ("Maladie+Remède", "Santé"), ("Humain+Médecine", "Santé"), ("Fruit+Humain", "Santé"),
  ("Temps+Vieillesse", "Mort"), ("Maladie+Vieillesse", "Mort"), ("Guerre+Humain", "Mort"),
  ("Humain+Temps+Temps", "Mort"),
  ("Humain+Mort+Terre", "Tombe"), ("Mort+Terre", "Tombe"), ("Mort+Pierre", "Tombe"),
  ("Humain+Mort+Pierre+Terre", "Tombe"),
  ("Mort+Tristesse", "Deuil"), ("Amour+Mort", "Deuil"), ("Famille+Mort", "Deuil"),
  ("Tombe+Tristesse", "Deuil"), ("Famille+Mort+Tombe+Tristesse", "Deuil"),
  ("Pensée+Son", "Langage"), ("Humain+Son", "Langage"), ("Humain+Humain+Pensée", "Langage"),
  ("Esprit+Pensée", "Conscience"), ("Humain+Pensée", "Conscience"),
  ("Cerveau+Esprit+Mémoire", "Conscience"), ("Cerveau+Cœur+Esprit+Humain", "Conscience"),
  ("Pensée+Éclair", "Idée"), ("Lumière+Pensée", "Idée"), ("Ampoule+Pensée", "Idée"),
  ("Pensée+Pensée", "Idée"),
  ("Enfant+Œil", "Curiosité"), ("Enfant+Pensée", "Curiosité"), 
  ("Idée+Œil", "Curiosité"),
  ("Cœur+Peur", "Courage"), ("Héros+Peur", "Courage"), ("Cœur+Lion", "Courage"),
  ("Chevalier+Peur", "Courage"),
  ("Pensée+Vieillesse", "Sagesse"), ("Livre+Vieillesse", "Sagesse"), ("Hibou+Humain", "Sagesse"),
  ("Mémoire+Temps+Vieillesse", "Sagesse"), ("Livre+Pensée+Temps+Vieillesse", "Sagesse"),

  # ---------- Outils et armes ----------
  ("Humain+Pierre", "Outil"), ("Bois+Humain", "Outil"), ("Humain+Métal", "Outil"),
  ("Bois+Humain+Pierre", "Outil"),
  ("Bois+Pierre", "Hache"), ("Arbre+Outil", "Hache"), ("Bois+Métal+Outil", "Hache"),
  ("Bois+Métal", "Marteau"), ("Métal+Outil", "Marteau"), ("Outil+Pierre", "Marteau"),
  ("Bois+Épée", "Lance"), ("Bois+Obsidienne", "Lance"), ("Bois+Outil+Pierre", "Lance"),
  
  ("Bois+Corde", "Arc"), ("Bois+Chasse", "Arc"), ("Bois+Corde+Humain", "Arc"),
  ("Humain+Arc", "Chasse"), ("Faim+Lance", "Chasse"), ("Chien+Humain", "Chasse"),
  ("Chasse+Mammifère", "Viande"), ("Chasse+Oiseau", "Viande"), ("Cochon+Hache", "Viande"),
  
  ("Humain+Poisson", "Pêche"), ("Bateau+Poisson", "Pêche"), ("Lance+Poisson", "Pêche"),
  ("Corde+Humain+Poisson", "Pêche"),
  ("Bois+Outil", "Roue"), ("Mouvement+Pierre", "Roue"), ("Bois+Mouvement", "Roue"),
  ("Bois+Roue", "Charrette"), ("Cheval+Roue", "Charrette"), ("Roue+Roue", "Charrette"),
  ("Bois+Cheval+Roue", "Charrette"),
  ("Bois+Eau", "Bateau"), ("Bois+Rivière", "Bateau"), ("Bois+Eau+Outil", "Bateau"),
  ("Tissu+Vent", "Voile"), ("Bateau+Vent", "Voile"), ("Bateau+Tissu", "Voile"),
  ("Bateau+Ville", "Port"), ("Bateau+Village", "Port"),
  ("Bateau+Bateau+Mer+Ville", "Port"),

  # ---------- Agriculture et cuisine ----------
  ("Humain+Plante", "Agriculture"), ("Outil+Terre", "Agriculture"), ("Graine+Humain", "Agriculture"),
  ("Eau+Humain+Plante", "Agriculture"), ("Eau+Humain+Plante+Terre", "Agriculture"),
  ("Agriculture+Terre", "Champ"), ("Agriculture+Blé", "Champ"), ("Agriculture+Sol fertile", "Champ"),
  
  ("Champ+Maison", "Ferme"), ("Agriculture+Maison", "Ferme"), ("Élevage+Maison", "Ferme"),
  ("Champ+Humain+Maison", "Ferme"), ("Champ+Humain+Maison+Vache", "Ferme"),
  ("Ferme+Oiseau", "Élevage"), ("Humain+Mouton", "Élevage"), ("Humain+Vache", "Élevage"),
  ("Ferme+Mammifère", "Élevage"), 
  ("Blé+Pierre", "Farine"), ("Blé+Moulin", "Farine"), ("Champ+Moulin", "Farine"),
  ("Blé+Pierre+Pierre", "Farine"),
  ("Roue+Vent", "Moulin"), ("Pierre+Roue", "Moulin"), ("Maison+Vent", "Moulin"),
  ("Maison+Roue+Vent", "Moulin"),
  ("Eau+Farine+Feu", "Pain"), ("Farine+Four", "Pain"), ("Farine+Levure", "Pain"),
  ("Eau+Farine+Four", "Pain"), ("Eau+Farine+Feu+Sel", "Pain"), ("Eau+Farine+Feu+Levure", "Pain"),
  ("Brique+Feu", "Four"), ("Brasier+Brique", "Four"),
  ("Argile+Feu+Pierre", "Four"),
  ("Argile+Humain", "Poterie"), ("Argile+Four", "Poterie"), ("Boue+Humain", "Poterie"),
  ("Boue+Four", "Brique"), ("Argile+Eau+Humain", "Poterie"),
  ("Bois+Feu+Pierre", "Feu de camp"), ("Feu+Tente", "Feu de camp"), ("Bois+Feu+Humain", "Feu de camp"),
  ("Brasier+Humain", "Feu de camp"),
  ("Four+Humain", "Cuisine"), ("Four+Maison", "Cuisine"), ("Feu de camp+Viande", "Cuisine"),
  ("Feu+Humain+Viande", "Cuisine"),
  ("Lait+Temps", "Fromage"), ("Bactérie+Lait", "Fromage"), ("Fermentation+Lait", "Fromage"),
  ("Lait+Sel+Temps", "Fromage"), ("Grotte+Lait+Sel+Temps", "Fromage"),
  ("Mammifère+Naissance", "Lait"), ("Élevage+Vache", "Lait"),
  ("Ferme+Vache", "Lait"),
  ("Raisin+Temps", "Vin"), ("Fermentation+Raisin", "Vin"), ("Fermentation+Vigne", "Vin"),
  ("Humain+Raisin+Temps", "Vin"), ("Bois+Fermentation+Raisin+Temps", "Vin"),
  ("Eau+Pain", "Bière"), ("Blé+Fermentation", "Bière"), ("Blé+Eau+Levure", "Bière"),
  ("Blé+Eau+Levure+Temps", "Bière"),
  ("Abeille+Fleur", "Miel"), ("Humain+Ruche", "Miel"),
  ("Olive+Pierre", "Huile"), ("Moulin+Olive", "Huile"), ("Moulin+Tournesol", "Huile"),
  ("Olive+Pression", "Huile"),

  # ---------- Artisanat ----------
  ("Humain+Tissu", "Vêtement"), ("Cuir+Humain", "Vêtement"), ("Fourrure+Humain", "Vêtement"),
  ("Tisserand+Tissu", "Vêtement"), ("Humain+Laine+Tisserand", "Vêtement"),
  ("Humain+Laine", "Tisserand"), ("Coton+Humain", "Tisserand"), ("Humain+Lin", "Tisserand"),
  ("Bois+Tissu", "Tente"), ("Bois+Cuir", "Tente"), ("Bois+Fourrure", "Tente"),
  ("Four+Métal", "Forge"), ("Four+Marteau", "Forge"), ("Fer+Four", "Forge"),
  ("Feu+Marteau+Métal", "Forge"), ("Feu+Marteau+Métal+Pierre", "Forge"),
  ("Forge+Humain", "Forgeron"), ("Humain+Marteau", "Forgeron"), ("Fer+Humain", "Forgeron"),
  ("Feu+Humain+Métal", "Forgeron"),
  ("Cire+Feu", "Bougie"), ("Cire+Corde", "Bougie"),
  ("Cire+Corde+Feu", "Bougie"),
  ("Mort+Désert", "Momie"), ("Mort+Tissu", "Momie"), ("Mort+Pharaon", "Momie"),
  ("Mort+Sel+Tissu", "Momie"), ("Mort+Pharaon+Sel+Tissu", "Momie"),

  # ---------- Habitat et société ----------
  ("Maison+Maison", "Village"), ("Famille+Famille", "Village"), ("Ferme+Ferme", "Village"),
  ("Maison+Maison+Maison", "Village"), ("Humain+Humain+Humain+Humain", "Village"),
  ("Village+Village+Village", "Ville"), ("Maison+Maison+Maison+Maison", "Ville"),
  ("Marché+Village", "Ville"),
  ("Brique+Brique", "Mur"), ("Ciment+Pierre", "Mur"), ("Brique+Ciment", "Mur"),
  ("Brique+Brique+Pierre", "Mur"),
  ("Mur+Mur", "Tour"), ("Brique+Brique+Brique", "Tour"), 
  ("Mur+Mur+Tour+Tour", "Château"), ("Roi+Tour", "Château"),
  ("Eau+Village", "Puits"), ("Pierre+Source", "Puits"), ("Eau+Outil+Pierre", "Puits"),
  ("Brique+Eau", "Puits"),
  ("Charrette+Terre", "Route"), ("Goudron+Pierre", "Route"), ("Charrette+Sable", "Route"),
  
  ("Eau+Route", "Pont"), ("Rivière+Route", "Pont"),
  ("Canyon+Route", "Pont"), ("Bois+Bois+Corde+Rivière", "Pont"),
  ("Village+Village", "Commerce"), ("Route+Village", "Commerce"), ("Monnaie+Marché", "Commerce"),
  ("Bateau+Port", "Commerce"),
  ("Commerce+Village", "Marché"), ("Commerce+Ville", "Marché"), ("Monnaie+Village", "Marché"),
  ("Commerce+Maison+Monnaie", "Marché"),
  ("Commerce+Métal", "Monnaie"), ("Commerce+Or", "Monnaie"), ("Humain+Or", "Monnaie"),
  ("Argent+Commerce", "Monnaie"), ("Feu+Marteau+Or", "Monnaie"),
  ("Humain+Pouvoir", "Roi"), ("Château+Humain", "Roi"), ("Héros+Ville", "Roi"),
  ("Château+Chevalier+Humain", "Roi"),
  ("Chevalier+Chevalier", "Armée"), ("Chevalier+Roi", "Armée"), ("Héros+Héros", "Armée"),
  ("Chevalier+Chevalier+Roi", "Armée"), ("Chevalier+Chevalier+Épée+Roi", "Armée"),
  ("Armée+Armée", "Guerre"), ("Armée+Colère", "Guerre"),
  ("Armée+Armée+Colère", "Guerre"), ("Armée+Épée+Feu+Ville", "Guerre"),
  ("Amour+Guerre", "Paix"), ("Guerre+Loi", "Paix"),
  ("Écriture+Loi+Roi+Roi", "Paix"),
  ("Livre+Ville", "Loi"), ("Écriture+Pierre+Village", "Loi"), ("Livre+Roi", "Loi"),
  ("Écriture+Pierre+Roi", "Loi"),
  ("Cheval+Héros", "Chevalier"), ("Cheval+Humain+Épée", "Chevalier"),
  

  # ---------- Religion et monuments ----------
  ("Dieu+Humain", "Religion"), ("Esprit+Humain", "Religion"), ("Humain+Mythe", "Religion"),
  ("Esprit+Humain+Mort", "Religion"), ("Dieu+Humain+Livre+Temple", "Religion"),
  ("Maison+Religion", "Temple"), ("Dieu+Maison", "Temple"), ("Marbre+Religion", "Temple"),
  ("Humain+Pierre+Pierre+Religion", "Temple"),
  ("Roi+Tombe", "Pyramide"), ("Pharaon+Tombe", "Pyramide"), ("Désert+Tombe", "Pyramide"),
  ("Désert+Pierre+Tombe", "Pyramide"), ("Désert+Pierre+Pierre+Roi", "Pyramide"),

  # ---------- Arts ----------
  ("Son+Émotion", "Musique"), ("Art+Son", "Musique"), ("Joie+Langage", "Musique"),
  ("Bois+Humain+Vent", "Musique"), ("Humain+Son+Émotion", "Musique"), ("Os+Vent", "Musique"),
  ("Idée+Émotion", "Art"), ("Musique+Peinture", "Art"), ("Peinture+Sculpture", "Art"),
  ("Humain+Idée+Émotion", "Art"),
  ("Arc-en-ciel+Art", "Peinture"), ("Art+Mur", "Peinture"),
  ("Art+Arc-en-ciel+Huile+Tissu", "Peinture"),
  ("Art+Pierre", "Sculpture"), ("Art+Marbre", "Sculpture"), ("Art+Bois", "Sculpture"),
  ("Art+Marteau+Pierre", "Sculpture"), ("Art+Humain+Marbre+Marteau", "Sculpture"),
  ("Art+Langage", "Théâtre"), ("Art+Mythe", "Théâtre"), ("Art+Humain+Émotion", "Théâtre"),
  ("Art+Émotion+Humain+Langage", "Théâtre"),

  # ---------- Savoir ----------
  ("Langage+Pierre", "Écriture"), ("Langage+Papier", "Écriture"), ("Encre+Langage", "Écriture"),
  ("Argile+Langage", "Écriture"), ("Humain+Langage+Outil", "Écriture"),
  ("Humain+Écriture", "Livre"), ("Papier+Écriture", "Livre"), ("Cuir+Écriture", "Livre"),
  ("Écriture+Papier+Papier", "Livre"),
  ("Enfant+Livre", "École"), ("Livre+Maison", "Bibliothèque"), ("Enfant+Sagesse", "École"),
  ("Enfant+Humain+Livre", "École"),
  ("École+Livre", "Science"), ("Curiosité+Livre", "Science"), ("Humain+Laboratoire", "Science"),
  ("Curiosité+Idée+Livre", "Science"), ("Curiosité+Idée+Laboratoire+Livre", "Science"),
  ("Remède+Science", "Médecine"), ("Santé+Science", "Médecine"), ("Livre+Remède", "Médecine"),
  ("Livre+Maladie+Remède", "Médecine"), ("Humain+Maladie+Remède+Science", "Médecine"),
  ("Pensée+Sagesse", "Philosophie"), ("Sagesse+Écriture", "Philosophie"), ("Curiosité+Sagesse", "Philosophie"),
  ("Conscience+Pensée", "Philosophie"), ("Pensée+Pensée+Sagesse", "Philosophie"),
  ("Philosophie+Science", "Mathématiques"), ("Monnaie+Écriture", "Mathématiques"),
  ("Monnaie+Pensée", "Mathématiques"), ("Pensée+Pyramide+Science", "Mathématiques"),
  ("Continent+Papier", "Carte"), ("Continent+Écriture", "Carte"), ("Explorateur+Papier", "Carte"),
  ("Continent+Océan+Écriture", "Carte"), ("Continent+Océan+Papier+Écriture", "Carte"),
  ("Aimant+Carte", "Boussole"), ("Aimant+Pôle", "Boussole"),
  ("Aimant+Eau+Métal", "Boussole"),
  ("Pierre+Temps+Écriture", "Calendrier"), ("Saison+Écriture", "Calendrier"), ("Lune+Écriture", "Calendrier"),
  ("Lune+Temps+Écriture", "Calendrier"), ("Lune+Soleil+Temps+Écriture", "Calendrier"),
  ("Roue+Temps", "Horloge"), ("Machine+Temps", "Horloge"), ("Métal+Roue+Temps", "Horloge"),
  ("Ombre+Soleil+Temps", "Horloge"),

  # ---------- Chemins supplémentaires ----------
  ("Cerveau+Cœur+Sang+Squelette", "Humain"),
  ("Bois+Brique+Brique", "Maison"), ("Humain+Pierre+Tente", "Maison"),
  ("Chevalier+Épée", "Héros"), ("Forgeron+Métal", "Épée"), ("Bateau+Déluge", "Arche"), ("Courage+Humain", "Héros"),
]
