# Recettes longues : une recette à 3 ingrédients (chapitres III-IV) ou à 4 (chapitres V-VII)
# pour chaque élément qui n’avait que des paires. Les pages du Livre visent ces tailles selon le chapitre.
# Ingrédients tirés du même chapitre ou d’un chapitre antérieur.
RECIPES = [
  # Formations Naturelles (chapitre III)
  ("Continent+Séisme+Neige", "Montagne"),
  ("Océan+Continent+Ciel", "Planète Terre"),
  ("Sable+Soleil+Sécheresse", "Désert"),
  ("Désert+Source+Ombre", "Oasis"),
  ("Falaise+Rivière+Gravité", "Cascade"),
  ("Mer+Sable+Soleil", "Plage"),
  ("Montagne+Érosion+Pluie", "Colline"),
  ("Glace+Montagne+Océan", "Iceberg"),
  ("Eau+Sel+Vague", "Mer"),
  ("Pluie+Pierre+Colline", "Source"),
  ("Océan+Volcan+Pression", "Source hydrothermale"),
  ("Volcan+Boue+Méthane", "Volcan de boue"),
  ("Sable+Vent+Désert", "Dune"),
  # Cosmos (chapitre III)
  ("Pierre+Métal+Espace", "Astéroïde"),
  ("Étoile+Explosion+Poussière", "Poussière d'étoiles"),
  ("Hydrogène+Hélium+Planète", "Jupiter"),
  ("Planète+Glace+Poussière", "Anneaux planétaires"),
  ("Supernova+Neutron+Onde", "Pulsar"),
  ("Masse+Ombre+Galaxie", "Matière noire"),
  ("Vide+Étoile+Planète", "Espace"),
  ("Astéroïde+Planète+Explosion", "Cratère"),
  ("Lune+Océan+Gravité", "Marée lunaire"),
  # Flore (chapitre IV)
  ("Graine+Pluie+Soleil", "Arbre"),
  ("Vigne+Soleil+Sucre", "Raisin"),
  ("Arbre+Fleur+Automne", "Pomme"),
  ("Plante+Racine+Sol fertile", "Légume"),
  ("Racine+Terre+Amidon", "Pomme de terre"),
  ("Graine+Temps+Force", "Chêne"),
  ("Plante+Falaise+Ombre", "Lierre"),
  ("Ombre+Pierre+Rosée", "Mousse"),
  ("Plante+Eau salée+Lumière", "Algue"),
  ("Fruit+Plante+Pollen", "Graine"),
  ("Fleur+Abeille+Soleil", "Fruit"),
  ("Arbre+Éclair+Vent", "Bois"),
  ("Bambou+Sucre+Soleil", "Canne à sucre"),
  ("Jardin+Fruit+Été", "Tomate"),
  ("Feuille+Feuille+Jardin", "Laitue"),
  ("Palmier+Plage+Graine", "Noix de coco"),
  ("Arbre+Sucre+Automne", "Érable"),
  ("Fleur+Rose+Tournesol", "Bouquet"),
  ("Graine+Sol fertile+Automne", "Citrouille"),
  # Biologie (chapitre IV)
  ("Cellule+Vie+Décomposition", "Bactérie"),
  ("Protéine+Catalyseur+Cellule", "Enzyme"),
  ("Feuille+Lumière+Cellule", "Chlorophylle"),
  ("Cellule+Eau+Particule", "Microbe"),
  ("Cellule+Cellule+ADN", "Reproduction"),
  ("Poule+Nid+Foin", "Œuf"),
  ("Gène+Évolution+Chaîne alimentaire", "Instinct"),
  ("Fleur+Abeille+Printemps", "Pollinisation"),
  # Vie et Créatures (chapitre IV)
  ("Sol fertile+Vie+Pluie", "Lombric"),
  ("Décomposition+Insecte+Œuf", "Asticot"),
  ("Papillon+Œuf+Feuille", "Chenille"),
  ("Poisson+Pôle+Froid", "Poisson Polaire"),
  ("Poisson+Vent+Vague", "Poisson Volant"),
  ("Lézard+Eau+Feu", "Salamandre"),
  ("Dinosaure+Ciel+Falaise", "Ptérodactyle"),
  ("Vie+Herbe+Pollen", "Insecte"),
  ("Lézard+Évolution+Herbe", "Serpent"),
  ("Lézard+Coquillage+Temps", "Tortue"),
  ("Lézard+Rivière+Dinosaure", "Crocodile"),
  ("Lézard+Fossile+Masse", "Dinosaure"),
  ("Oiseau+Banquise+Poisson", "Pingouin"),
  ("Chien+Lune+Forêt", "Loup"),
  ("Ours+Neige+Pôle", "Ours polaire"),
  ("Oiseau+Nid+Vent", "Plume"),
  ("Araignée+Soie+Rosée", "Toile d'araignée"),
  ("Poisson+Lézard+Cuir", "Écaille"),
  ("Oiseau+Vague+Poisson", "Oiseau marin"),
  ("Mouton+Montagne+Falaise", "Chèvre"),
  ("Oiseau+Lac+Nénuphar", "Canard"),
  ("Cheval+Ombre+Lumière", "Zèbre"),
  ("Chat+Jungle+Force", "Tigre"),
  ("Mammifère+Glace+Poisson", "Phoque"),
  ("Oiseau+Jungle+Arc-en-ciel", "Perroquet"),
  ("Escargot+Mer+Calcaire", "Coquillage"),
  ("Oiseau+Extinction+Île", "Dodo"),
  ("Œuf+Poule+Chaleur", "Poussin"),
  ("Étoile+Plage+Vie", "Étoile de mer"),
  ("Chien+Forêt+Poule", "Renard"),
  ("Insecte+Été+Son", "Cigale"),
  # Corps et Esprit (chapitre V)
  ("Cœur+Eau+Fer+Cellule", "Sang"),
  ("Muscle+Sang+Pression+Vie", "Cœur"),
  ("Cellule+Lentille+Lumière+Cerveau", "Œil"),
  ("Protéine+Force+Humain+Mouvement", "Muscle"),
  ("Os+Os+Calcium+Humain", "Squelette"),
  ("Cellule+Électricité+Cerveau+Organisme", "Neurone"),
  ("Cerveau+Neurone+Conscience+Langage", "Pensée"),
  ("Cerveau+Temps+Enfant+Vieillesse", "Mémoire"),
  ("Sommeil+Nuit+Pensée+Nuage", "Rêve"),
  ("Cœur+Cerveau+Joie+Peur", "Émotion"),
  ("Émotion+Larme+Pluie+Deuil", "Tristesse"),
  ("Émotion+Sang+Feu+Tonnerre", "Colère"),
  ("Cœur+Cœur+Rose+Émotion", "Amour"),
  ("Enfant+Œil+Chat+Idée", "Curiosité"),
  ("Cœur+Peur+Lion+Épée", "Courage"),
  ("Humain+Épée+Sang+Larme", "Douleur"),
  ("Joie+Son+Enfant+Jeu", "Rire"),
  ("Rêve+Peur+Nuit+Ombre", "Cauchemar"),
  ("Humain+Sport+Chaleur+Sel", "Sueur"),
  ("Tissu+Sang+Colle+Médecine", "Pansement"),
  # Créations Humaines (chapitre V)
  ("Poisson+Verre+Eau+Algue", "Aquarium"),
  ("Or+Roi+Diamant+Forgeron", "Couronne"),
  ("Glace+Brique+Neige+Hiver", "Igloo"),
  ("Sable+Verre+Temps+Gravité", "Sablier"),
  ("Verre+Plante+Chaleur+Lumière", "Serre"),
  ("Cochon+Monnaie+Céramique+Enfant", "Tirelire"),
  ("Parapluie+Soleil+Plage+Ombre", "Parasol"),
  ("Lion+Éléphant+Girafe+Parc", "Zoo"),
  ("Bois+Soufre+Phosphore+Friction", "Allumette"),
  ("Acier+Feu+Marteau+Forgeron", "Épée"),
  ("Argile+Sable+Eau+Four", "Brique"),
  ("Fer+Bois+Outil+Force", "Marteau"),
  ("Bois+Fer+Outil+Mouvement", "Roue"),
  ("Tissu+Vent+Bateau+Corde", "Voile"),
  ("Agriculture+Sol fertile+Graine+Pluie", "Champ"),
  ("Chasse+Mammifère+Couteau+Muscle", "Viande"),
  ("Vache+Chèvre+Herbe+Ferme", "Lait"),
  ("Abeille+Fleur+Ruche+Pollen", "Miel"),
  ("Monnaie+Marché+Route+Bateau", "Commerce"),
  ("Pierre+Goudron+Sable+Charrette", "Route"),
  ("Bois+Tissu+Corde+Feu de camp", "Tente"),
  ("Humain+Arc+Cerf+Faim", "Chasse"),
  ("Humain+Mouton+Vache+Chien", "Élevage"),
  ("Humain+Laine+Coton+Tissu", "Tisserand"),
  ("Maïs+Feu+Huile+Sel", "Pop-corn"),
  ("Sucre+Chaleur+Beurre+Sel", "Caramel"),
  ("Bambou+Tisserand+Corde+Pomme", "Panier"),
  ("Bronze+Son+Forgeron+Église", "Cloche"),
  ("Lait+Mouvement+Sel+Fermier", "Beurre"),
  ("Farine+Œuf+Eau+Sel", "Pâtes"),
  ("Fruit+Pomme+Pression+Verre", "Jus de fruit"),
  ("Pain+Viande+Salade+Fromage", "Sandwich"),
  ("Bois+Sommeil+Tissu+Plume", "Lit"),
  ("Bois+Clou+Menuisier+Maison", "Porte"),
  ("Verre+Bois+Maison+Lumière", "Fenêtre"),
  ("Métal+Forge+Porte+Trésor", "Clé"),
  ("Pluie+Tissu+Métal+Bois", "Parapluie"),
  ("Humain+Blé+Vache+Ferme", "Fermier"),
  ("Lit+Médecine+Maladie+Maison", "Hôpital"),
  ("Acier+Bois+Route+Clou", "Rails"),
  ("Cuir+Air+Jeu+Enfant", "Ballon"),
  ("Neige+Hiver+Enfant+Charbon", "Bonhomme de neige"),
  ("Poisson+Riz+Algue+Couteau", "Sushi"),
  ("Métal+Lombric+Poisson+Corde", "Hameçon"),
  ("Cuir+Caoutchouc+Corde+Humain", "Chaussure"),
  ("Caoutchouc+Chaussure+Boue+Pluie", "Botte"),
  ("Laine+Tisserand+Chaussure+Froid", "Chaussette"),
  ("Coton+Tissu+Médecine+Laboratoire", "Blouse blanche"),
  ("Cuir+Monnaie+Or+Argent", "Porte-monnaie"),
  ("Humain+Pain+Four+Farine", "Boulanger"),
  ("Humain+Cuisine+Couteau+Soupe", "Cuisinier"),
  ("Humain+Brasier+Eau+Courage", "Pompier"),
  ("Humain+Médecine+Remède+Maladie", "Médecin"),
  ("Humain+Brique+Ciment+Mur", "Maçon"),
  ("Humain+Ciel+Vitesse+Courage", "Pilote"),
  ("Rails+Ville+Horloge+Maison", "Gare"),
  ("Château+Temps+Guerre+Lierre", "Ruine"),
  ("Cuisinier+Maison+Vin+Monnaie", "Restaurant"),
  ("Encre+Plastique+Métal+Écriture", "Stylo"),
  ("Papier+Encre+Écriture+Jour", "Journal"),
  ("Écriture+Langage+Son+École", "Alphabet"),
  ("Livre+Alphabet+Langage+École", "Dictionnaire"),
  ("Humain+Espace+Lune+Courage", "Astronaute"),
  ("Rhum+Jus de fruit+Glace+Sucre", "Cocktail"),
  ("Livre+Livre+Bois+Sagesse", "Bibliothèque"),
  ("Verre+Argent+Lumière+Œil", "Miroir"),
  ("Couteau+Couteau+Clou+Papier", "Ciseaux"),
  ("Ours+Tissu+Coton+Enfant", "Ours en peluche"),
  ("Papier+Papier+Écriture+École", "Cahier"),
  ("Bois+Fer+Outil+Terre", "Pelle"),
  ("Cacao+Sucre+Beurre+Moulin", "Chocolat"),
  ("Eau+Marbre+Sculpture+Parc", "Fontaine"),
  ("Tombe+Tombe+Deuil+Église", "Cimetière"),
  ("Bois+Graphite+Écriture+Art", "Crayon"),
  ("Humain+Argile+Four+Roue", "Potier"),
  ("Humain+Hache+Forêt+Chêne", "Bûcheron"),
  ("Caoutchouc+Crayon+Papier+École", "Gomme"),
  ("Acier+Forgeron+Chevalier+Guerre", "Armure"),
  ("Château+Eau+Crocodile+Pelle", "Douves"),
  ("Pont+Douves+Poulie+Corde", "Pont-levis"),
  ("Corde+Roue+Force+Outil", "Poulie"),
  ("Papier+Corde+Ours en peluche+Amour", "Cadeau"),
  ("Muscle+Jeu+Ballon+Sueur", "Sport"),
  ("Chaussure+Acier+Glace+Hiver", "Patin à glace"),
  ("Ballon+Chaussure+Herbe+Jeu", "Football"),
  ("Bois+Foin+Blé+Ferme", "Grange"),
  ("Rose+Alcool+Distillation+Verre", "Parfum"),
  # Histoire (chapitre VI)
  ("Civilisation+Pyramide+Temple+Philosophie", "Antiquité"),
  ("Fission nucléaire+Radioactivité+Civilisation+Science", "Ère atomique"),
  # Technologie (chapitre VI)
  ("Machine à vapeur+Charbon+Fer+Rails", "Locomotive"),
  ("Locomotive+Rails+Gare+Charrette", "Train"),
  ("Moteur+Roue+Route+Pétrole", "Voiture"),
  ("Ordinateur+Téléphone+Toile d'araignée+Planète Terre", "Internet"),
  ("Ordinateur+Neurone+Pensée+Puce électronique", "Intelligence artificielle"),
  ("Moulin+Vent+Électricité+Acier", "Éolienne"),
  ("Lentille+Lentille+Cellule+Laboratoire", "Microscope"),
  ("Bateau+Acier+Pression+Poisson Abyssal", "Sous-marin"),
  ("Fission nucléaire+Explosion+Guerre+Radioactivité", "Bombe atomique"),
  ("Silicium+Cuivre+Électron+Ordinateur", "Puce électronique"),
  ("Mémoire+Ordinateur+Clé+Puce électronique", "Sauvegarde"),
  ("Moteur+Vélo+Vitesse+Pétrole", "Moto"),
  ("Bateau+Machine à vapeur+Charbon+Rivière", "Bateau à vapeur"),
  ("Radio+Télescope+Onde+Galaxie", "Radiotélescope"),
  ("Moteur+Champ+Roue+Fermier", "Tracteur"),
  ("Ampoule+Route+Nuit+Électricité", "Lampadaire"),
  ("Tracteur+Blé+Champ+Machine", "Moissonneuse-batteuse"),
  ("Sous-marin+Miroir+Lentille+Œil", "Périscope"),
  # Légendes (chapitre VII)
  ("Lion+Humain+Pyramide+Mythe", "Sphinx"),
  ("Énergie+Vie+Mythe+Poussière d'étoiles", "Magie"),
  ("Air+Vie+Conscience+Rêve", "Esprit"),
  ("Magie+Esprit+Énergie+Source", "Mana"),
  ("Cristal+Mana+Lumière+Verre", "Orbe"),
  ("Bois+Magie+Fée+Poussière d'étoiles", "Baguette"),
  ("Magie+Force+Couronne+Énergie", "Pouvoir"),
  ("Or+Diamant+Forgeron+Amour", "Anneau"),
  ("Feu+Magie+Arc-en-ciel+Feu follet", "Feu Magique"),
  ("Religion+Pouvoir+Ciel+Univers", "Dieu"),
  ("Géant+Faim+Enfant+Forêt", "Ogre"),
  ("Chat+Botte+Épée+Château", "Chat botté"),
  ("Cire+Plume+Soleil+Grèce antique", "Ailes d'Icare"),
]
