# Recettes : rattrapage (objets du quotidien et éléments dessinés)
# Recherche, deux contre-vérifications indépendantes, validation du propriétaire.
RECIPES = [
  ("Livre+Livre", "Bibliothèque"),
  ("Argent+Verre", "Miroir"),
  ("Huile+Lumière+Poterie", "Lampe à huile"),
  ("Cuisine+Épée", "Couteau"),
  ("Couteau+Couteau", "Ciseaux"),
  ("Ours+Tissu", "Ours en peluche"),
  ("Papier+École", "Cahier"),
  ("Neige+Outil", "Pelle"),
  ("Outil+Sable", "Pelle"),
  ("Ampoule+Loi+Route", "Feu tricolore"),
  ("Cacao+Sucre", "Chocolat"),
  ("Fermentation+Pomme", "Cidre"),
  ("Jardin+Ville", "Parc"),
  ("Arbre+Mammifère+Savane", "Girafe"),
  ("Champ+Moteur", "Tracteur"),
  ("Agriculture+Moteur", "Tracteur"),
  ("Chaleur+Chocolat+Lait", "Chocolat chaud"),
  ("Feu+Fruit+Sucre", "Confiture"),
  ("Huile+Mouvement+Œuf", "Mayonnaise"),
  ("Eau+Sculpture", "Fontaine"),
  ("Tombe+Tombe", "Cimetière"),
  ("Ampoule+Route", "Lampadaire"),
  ("Bois+Graphite", "Crayon"),
  ("Humain+Poterie", "Potier"),
  ("Hache+Humain", "Bûcheron"),
  ("Chien+Humain+Mouton", "Berger"),
  ("Humain+Pêche", "Pêcheur"),
  ("Chenille+Tisserand", "Soie"),
  ("Caoutchouc+Graphite", "Gomme"),
  ("Lumière+Tour", "Phare"),
  ("Mer+Étoile", "Étoile de mer"),
  ("Océan+Étoile", "Étoile de mer"),
  ("Mammifère+Poule", "Renard"),
  ("Glace+Route", "Verglas"),
  ("Glacier+Mer+Vallée", "Fjord"),
  ("Forêt+Froid", "Taïga"),
  ("Chaleur+Désert+Lumière", "Mirage"),
  ("Son+Éclair", "Tonnerre"),
  ("Plage+Vent", "Dune"),
  ("Air+Chaleur+Tissu", "Montgolfière"),
]
