# Énigmes des pages du Livre : {nom: énigme}. Une page à trouver montre l’énigme de son élément.
# Règles (vérifiées par check.py et gen_seed.py) : 80 caractères au plus, ni le nom de l’élément
# ni celui d’un de ses ingrédients ; on évoque, on ne nomme pas. Un élément sans énigme garde l’indice des familles.

RIDDLES = {
  # Matériaux
  "Boue": "Les cochons s’y vautrent de bonheur ; tes bottes, beaucoup moins.",
  "Lave": "Rivière ardente vomie par le volcan ; refroidie, je deviens roche noire.",
  "Vapeur": "Je m’élève en soupirant et je meurs en perles sur les vitres froides.",
  "Poussière": "Je danse dans le rayon de lumière et m’endors sous les meubles oubliés.",
  "Fumée": "Pas de moi sans flamme, dit-on ; je grimpe en volutes grises et pique les yeux.",
  "Pierre": "Roulante, je n’amasse pas mousse ; on me jette parfois la première.",
  "Sable": "Je file entre tes doigts, je compte les heures, je bâtis des châteaux d’un jour.",
  "Cendre": "Ce qui reste quand la flamme a tout dévoré ; le phénix renaît de moi.",
  "Métal": "Froid au toucher, je tinte sous le marteau et j’attire la foudre.",
  "Verre": "Transparent mais têtu, je laisse passer le jour et me brise en mille éclats.",
  "Cristal": "Je tinte quand on trinque, et le flocon de neige est mon petit cousin.",
  "Magma": "Je bouillonne sous tes pieds en attendant que le volcan m’ouvre la porte.",
  "Argile": "Pétris-moi, tourne-moi, cuis-moi : je deviens bol, brique ou statuette.",
  "Charbon": "Noir trésor des mineurs, je finis dans la chaussette des enfants pas sages.",
  "Sel": "Je pique les plaies, je fais fondre le verglas et je relève ta soupe.",
  "Fer": "Ton sang me porte, la pluie me fait rougir ; bats-moi tant que je suis chaud !",
  "Cuivre": "Rose orangé, je file le courant et je verdis en vieillissant sur les toits.",
  "Or": "Le silence me vaut, dit-on ; les chercheurs de pépites me traquent au tamis.",
  "Argent": "Je ne fais pas le bonheur, dit-on, mais je fais fuir les loups-garous.",
  "Étain": "Plie-moi, je crie tout bas ; marie-moi au roux et naît l’âge du bronze.",
  "Bronze": "Médaille du troisième, je fais sonner les cloches et j’ai nommé tout un âge.",
  "Acier": "Lame, poutre ou ressort : je suis le muscle des gratte-ciel et le fil des épées.",
  "Plomb": "Gris et si lourd, je fais les petits soldats et les rêves des alchimistes.",
  "Calcaire": "Je tache de blanc ta bouilloire et je dresse les falaises d’Étretat.",
  "Marbre": "Froid et veiné, j’ai offert David à Michel-Ange. Rien ne m’émeut.",
  "Granite": "Moucheté gris et rose, je borde la côte bretonne et les cuisines chics.",
  "Obsidienne": "Noire et luisante, miroir de sorcière, je taillais les lames aztèques.",
  "Quartz": "Je bats la seconde au cœur des montres et je fleuris en pointes laiteuses.",
  "Diamant": "Je raye tout et rien ne me raye ; on dit que je suis éternel.",
  "Graphite": "Je suis l’âme grise de ton crayon, et la gomme est mon ennemie.",
  "Pétrole": "Or noir jaillissant du désert, je fais rouler le monde et pleurer les mouettes.",
  "Goudron": "Noir et collant, je tapisse les routes ; avec des plumes, je punis les bandits.",
  "Béton": "Gris et coulé, je fais les tours ; un alibi taillé en moi est inattaquable.",
  "Ciment": "Poudre grise, je durcis au contact de l’onde et je lie les briques entre elles.",
  "Plâtre": "Blanc comme un fantôme, je tiens ta jambe cassée et je lisse les murs.",
  "Céramique": "Terre cuite émaillée, je deviens tasse, carreau ou vase sous la main du potier.",
  "Porcelaine": "Si fine que le jour me traverse ; un éléphant chez moi, quelle catastrophe !",
  "Papier": "Lettre, avion ou cocotte pliée : j’enveloppe la roche, le ciseau me tranche.",
  "Encre": "Je fais couler les plumes et noircis les pages ; la seiche me crache pour fuir.",
  "Cire": "Les abeilles me bâtissent en hexagones ; je pleure au pied des chandelles.",
  "Caoutchouc": "Je rebondis, je m’étire, je gomme tes fautes et je chausse les voitures.",
  "Plastique": "Je suis partout, je dure des siècles ; les tortues me prennent pour des méduses.",
  "Laine": "Pelote pour les chats, pull qui gratte : la brebis me porte avant toi.",
  "Coton": "Doux flocon cueilli dans les champs, je deviens ton tee-shirt préféré.",
  "Tissu": "Trame et chaîne entrelacées, je deviens robe, drap ou rideau.",
  "Cuir": "Jadis peau, me voilà blouson de motard, ceinture ou botte qui craque.",
  "Corde": "Je tire les cloches, j’amarre les navires et je fais sauter les écoliers.",
  "Rouille": "Lèpre rousse des grilles oubliées, je ronge les clous et les vieux vélos.",
  "Pierre ponce": "Roche, je flotte pourtant, et je râpe la corne de tes talons.",
  "Compost": "Épluchures et vers de terre me fabriquent ; je rends au jardin ce qu’il a donné.",
  "Sédiment": "Grain à grain, je me dépose au fond des eaux et j’écris l’histoire en strates.",
  "Suie": "Je noircis les cheminées et les joues des ramoneurs.",
  "Résine": "Larme dorée des conifères, je colle aux doigts et parfume les pinèdes.",
  "Ambre": "Miel de pierre, je garde un moustique captif depuis l’ère des dinosaures.",
  "Soie": "Un ver m’a filée pour toi ; je glisse sur la peau et j’ai nommé une route.",
  "Colle": "En tube ou en pot, je tiens tout ensemble ; gare à tes doigts, je ne lâche rien.",
  "Contreplaqué": "Feuilles minces aux fibres croisées, je suis l’étagère qui ne gondole pas.",
  "Foin": "Chercher une aiguille en moi ? Bon courage ! Les vaches me croquent l’hiver.",
  "Silex": "Frappé, je crache des étincelles ; l’homme des cavernes m’a taillé en pointes.",
  "Ocre": "Jaune ou rouge, j’ai coloré les bisons de Lascaux et les villages du Roussillon.",

  # Phénomènes Naturels
  "Pollution": "Je noircis les poumons des cités et j’irise les rivières d’huile.",
  "Pluie": "Je tambourine aux carreaux ; les escargots sortent, les pique-niques rentrent.",
  "Nuage": "Mouton de coton qui broute le bleu ; vois-tu le dragon que je deviens ?",
  "Énergie": "Einstein m’a mise en équation ; rien ne se perd, je change de costume.",
  "Vent": "Invisible, je fais danser les blés, voler les chapeaux et tourner les moulins.",
  "Bourrasque": "Soudain coup d’épaule du ciel : ton parapluie se retourne en tulipe !",
  "Tempête": "Volets qui claquent, marins qui prient… parfois je tiens dans un verre d’eau.",
  "Éclair": "Zigzag aveuglant du ciel, ou chou fourré au café : je file en un instant.",
  "Tornade": "Entonnoir furieux, j’ai emporté Dorothée et son chien bien loin du Kansas.",
  "Explosion": "Boum ! En un instant tout vole en éclats ; il ne reste qu’un visage noirci.",
  "Incendie": "Sirènes hurlantes, grande échelle : les pompiers accourent pour m’éteindre.",
  "Brasier": "Ardent foyer qui rougeoie et crépite ; approche-toi, mais pas trop !",
  "Geyser": "Le sol gronde et crache un jet brûlant vers le ciel ; l’Islande m’a nommé.",
  "Vague": "Je roule, je déferle, je m’échoue ; les surfeurs guettent ma crête.",
  "Ozone": "Bouclier bleu tissé là-haut ; on s’inquiète d’un trou dans mon manteau.",
  "Lumière": "Je file à trois cent mille kilomètres par seconde et je fais fuir l’ombre.",
  "Arc-en-ciel": "Écharpe à sept couleurs après l’averse ; un lutin cache son or à mon pied.",
  "Temps": "Je file sans bruit ; on prétend me tuer, me perdre ou me gagner.",
  "Neige": "Je tombe en flocons muets ; les enfants me roulent en bonhomme à nez carotte.",
  "Glace": "Je tinte dans les verres, je porte les patineurs et je fonds en cornet.",
  "Blizzard": "Tourbillon blanc qui gifle et aveugle ; tu ne vois plus le bout de tes moufles.",
  "Tsunami": "Un mot japonais ; l’estran se vide, puis un mur liquide engloutit la côte.",
  "Déluge": "Quarante jours sans éclaircie ; Noé a bâti son arche pour me survivre.",
  "Brouillard": "Purée de pois sur Londres : tu n’y vois plus le bout de ton nez.",
  "Rosée": "Perles d’aube semées sur les prés ; le premier rayon me boit.",
  "Givre": "Je brode des fougères blanches sur les vitres et sucre les prés à l’aube.",
  "Grêle": "Billes blanches tombées du ciel : je cabosse les voitures et hache les vignes.",
  "Orage": "Après la lourdeur d’août, le ciel gronde et se zèbre ; compte les secondes !",
  "Ouragan": "On me donne un prénom, et mon œil reste calme quand tout tourne autour.",
  "Séisme": "Le sol frissonne, la vaisselle danse ; Richter me note sur son échelle.",
  "Érosion": "Patiente sculptrice, je ronge falaises et sommets grain après grain.",
  "Marée": "Deux fois par jour je m’en vais et reviens ; le Mont-Saint-Michel m’attend.",
  "Chaleur": "Je fais perler les fronts, onduler le bitume et fondre les sorbets.",
  "Froid": "Je rougis les nez, je fais claquer les dents et fumer les haleines.",
  "Sécheresse": "Le sol se fend en puzzle, les puits soupirent : pas une goutte depuis mai.",
  "Inondation": "Le fleuve sort de son lit et visite les salons ; on rame dans la rue.",
  "Avalanche": "Un cri de trop sur la pente, et tout le manteau blanc dévale en grondant.",
  "Glissement de terrain": "Après l’averse, le coteau lâche prise et dévale, emportant routes et maisons.",
  "Saison": "Nous sommes quatre sœurs qui se passent le relais ; Vivaldi nous a chantées.",
  "Jour": "Je commence au chant du coq et cède ma place quand les étoiles s’allument.",
  "Nuit": "Les hiboux veillent, tous les chats sont gris et les rêves prennent le relais.",
  "Ombre": "Je te suis partout sans bruit ; Peter Pan m’a perdue un soir.",
  "Son": "Je voyage jusqu’à tes oreilles ; dans le vide, nul ne m’entend.",
  "Écho": "Crie « Ohé ! » face au vide : je te le rends, un peu plus faible… faible…",
  "Feu de forêt": "Les pins crépitent en août ; les Canadair plongent dans la rade pour m’éteindre.",
  "Pluie acide": "Averse au goût de citron amer : je ronge les statues et roussis les sapins.",
  "Hiver": "Écharpes, moufles et chocolat chaud : les ours dorment pendant que je règne.",
  "Printemps": "Les bourgeons éclatent, les hirondelles reviennent et l’on change d’heure.",
  "Été": "Cigales, grandes vacances et glaces qui coulent sur les doigts.",
  "Automne": "Je roussis les bois, gonfle les champignons et ramène les cartables.",
  "Ciel": "Grand plafond bleu sans fin ; les oiseaux y nagent et les étoiles s’y piquent.",
  "Coucher de soleil": "L’astre du jour plonge à l’horizon et peint l’ouest d’orange et de rose.",
  "Verglas": "Patinoire invisible sur le bitume : à l’aube, les voitures valsent.",
  "Mirage": "Au loin, un lac miroite sur le sable… approche, et je m’évapore.",
  "Tonnerre": "Je roule après le zigzag céleste ; le capitaine Haddock m’invoque à Brest !",
  "Buée": "Souffle sur la vitre : j’apparais, et tu peux y dessiner un cœur.",
  "Feu follet": "Petite flamme bleue qui danse sur la tourbière ; ne la suis pas la nuit !",

  # Physique
  "Atome": "Les Grecs me croyaient insécable ; on m’a pourtant coupé, et ça a fait boum.",
  "Électron": "Minuscule et négatif, je tourne en nuage et je cours dans tes câbles.",
  "Proton": "Positif de nature, je trône au cœur de la matière et donne son numéro à chacun.",
  "Neutron": "Ni plus ni moins, je dors au cœur de la matière et brise l’uranium.",
  "Noyau atomique": "Cœur dense et minuscule au milieu d’un immense vide ; me briser libère l’enfer.",
  "Particule": "Les nobles me portent devant leur nom ; sous Genève, on me fait percuter.",
  "Onde": "Je pars en cercles du caillou jeté et je file sans rien emporter.",
  "Magnétisme": "Force invisible, je fais danser les aurores et pointer l’aiguille vers le nord.",
  "Aimant": "Je retiens tes dessins sur le frigo ; deux de mes pôles pareils se fuient.",
  "Électricité": "Je cours dans les fils, j’allume tes lampes et je picote les doigts curieux.",
  "Pression": "Je bouche tes oreilles en plongée et je fais siffler la cocotte-minute.",
  "Gravité": "Newton m’a reçue sur la tête ; c’est moi qui te ramène au sol après chaque saut.",
  "Masse": "Sur la Lune tu pèses moins, mais moi je ne change pas d’un gramme.",
  "Force": "Pousse, tire, soulève… Que je sois avec toi, jeune padawan !",
  "Mouvement": "Rien ne tient en place quand je passe : la feuille tombe, le cœur bat, tu cours.",
  "Vitesse": "Les radars me guettent et le guépard me porte comme une médaille.",
  "Friction": "Frotte tes mains l’hiver : je les réchauffe et j’use tes semelles.",
  "Plasma": "Quatrième état de la matière, je brille dans les néons et les aurores.",
  "Radiation": "Je rayonne en tous sens, invisible ; le trèfle jaune et noir te met en garde.",
  "Radioactivité": "Marie Curie m’a apprivoisée ; certains cailloux crépitent sous le Geiger.",
  "Fusion nucléaire": "Deux cœurs minuscules s’unissent, et le Soleil brille : c’est mon secret.",
  "Fission nucléaire": "Je casse l’uranium en deux, et les centrales en tirent leur courant.",
  "Lentille": "Bombée comme une petite graine, je grossis la fourmi sous l’œil du curieux.",
  "Prisme": "Un rayon blanc entre par ma face, il sort en sept couleurs ; Pink Floyd m’adore.",
  "Spectre lumineux": "Du rouge au violet, toutes les couleurs rangées en ruban, comme un éventail.",
  "Infrarouge": "Invisible à tes yeux, je trahis les corps tièdes aux lunettes de nuit.",
  "Ultraviolet": "Je dore ta peau et la brûle si tu oublies ta crème ; les abeilles me voient.",
  "Rayons X": "Je traverse ta chair et montre tes os au docteur ; Superman voit grâce à moi.",
  "Vide": "Rien, absolument rien : l’espace entre les astres, ou ton frigo un lundi soir.",
  "Gaz": "Sans forme, je remplis tout le flacon et m’échappe dès qu’on l’ouvre.",
  "Liquide": "Je prends la forme du verre qui m’accueille et je coule entre tes doigts.",
  "Solide": "Je garde ma forme quoi qu’il arrive ; tu peux t’asseoir sur moi sans couler.",
  "Température": "Le mercure me raconte ; quand je grimpe à 39, tu files sous la couette.",
  "Inertie": "Le bus freine, et tu continues tout seul vers l’avant : c’est encore moi.",
  "Relativité": "E = mc², c’est ma signature ; Einstein m’a fait courber l’espace.",
  "Physique quantique": "Un chat à la fois mort et vivant dans sa boîte : bienvenue chez moi.",
  "Antimatière": "Reflet inversé de tout ; si je touche mon jumeau, pouf, un éclair de clarté !",
  "Électricité statique": "Je dresse tes cheveux sur ta tête et je te pique quand tu touches la poignée.",
  "Bulle de savon": "Sphère irisée qu’un souffle libère ; elle danse, elle brille, et pop !",

  # Chimie
  "Hydrogène": "Le plus léger de tous, premier de la liste ; le Hindenburg s’en souvient encore.",
  "Oxygène": "Tu me prends à chaque inspiration ; sans moi, nulle flamme ne danse.",
  "Carbone": "Mine de crayon ou bague de fiançailles : c’est toujours moi, en habit différent.",
  "Azote": "Quatre bouffées sur cinq de ton souffle, c’est moi, discret et paresseux.",
  "Hélium": "Une bouffée de moi, et ta voix devient celle d’un canard de dessin animé !",
  "Sodium": "Métal si mou qu’on le coupe au couteau ; jeté dans l’eau, je pique une colère.",
  "Chlore": "L’odeur des piscines, c’est moi : je chasse les microbes et rougis tes yeux.",
  "Calcium": "Je bâtis tes dents et ton squelette ; un grand verre blanc au goûter me livre.",
  "Silicium": "Ma vallée californienne pense pour le monde entier, puce après puce.",
  "Soufre": "Jaune vif, je sens l’œuf pourri, et l’on dit que le diable m’adore.",
  "Phosphore": "Je luis tout seul dans le noir et je dors au bout de chaque allumette.",
  "Molécule": "Bande de copains liés pour la vie ; H₂O est la plus célèbre d’entre nous.",
  "Réaction chimique": "Ça mousse, ça fume, ça change de couleur : la matière fait peau neuve !",
  "Combustion": "Tout ce qui brûle passe entre mes mains et finit en cendres et en volutes.",
  "Oxydation": "Rouille sur le vélo, chair brunie du fruit croqué : c’est mon œuvre lente.",
  "Acide": "Je pince la langue comme un citron et je ronge le marbre sans pitié.",
  "Base chimique": "Je glisse sous les doigts et je bleuis le tournesol ; l’acide me fuit.",
  "Dioxyde de carbone": "Je pétille dans ta limonade et je réchauffe un peu trop la planète.",
  "Méthane": "Les rots des ruminants me libèrent ; je danse en flamme bleue sous la casserole.",
  "Ammoniac": "Mon odeur te pique le nez dans les litières et les produits ménagers.",
  "Eau salée": "Les larmes et l’océan ont mon goût ; je pique les yeux du nageur.",
  "Solution": "Le grain blanc fond dans ton thé et nage en moi. Je suis aussi la réponse !",
  "Distillation": "Mon alambic chauffe, la buée s’élève puis retombe goutte à goutte, pure.",
  "Cristallisation": "Laisse dormir le bocal : des géométries scintillantes y poussent en silence.",
  "Catalyseur": "Je presse les autres de changer et je ressors intact, tel un entremetteur.",
  "Alcool": "Je réchauffe les fêtes, fais tourner les têtes et nettoie les plaies en piquant.",
  "Sucre": "Les dentistes me craignent, les fourmis me suivent, ton café me réclame.",
  "Amidon": "Je rends la pomme de terre farineuse et la chemise raide sous le fer.",
  "Savon": "Je glisse des mains, je mousse et je fais fuir les microbes en chantant.",
  "Vinaigre": "Je pique la salade, je fais grimacer et j’adore les cornichons.",
  "Engrais": "Je fais grossir les citrouilles ; le jardinier me sème au pied des rosiers.",
  "Poudre à canon": "Noire, venue de Chine, je fais tonner les mousquets et fleurir les fusées.",
  "Polymère": "Une chaîne de mille maillons identiques : nylon, caoutchouc, bouteille…",
  "Tableau périodique": "Mendeleïev m’a rangé en cases ; chaque élément y a sa place, même les absents.",
  "Laboratoire": "Blouses blanches, fioles fumantes et éprouvettes : voici l’antre du savant.",
}
