# Énigmes des pages du Livre : {nom: énigme}. Une page à trouver montre l’énigme de son élément.
# Règles (vérifiées par check.py et gen_seed.py) : 80 caractères au plus, ni le nom de l’élément
# ni celui d’un de ses ingrédients ; on évoque, on ne nomme pas. Un élément sans énigme garde l’indice des familles.

RIDDLES = {
  # Matériaux
  "Boue": "Les cochons s’y vautrent de bonheur ; tes bottes, beaucoup moins.",
  "Lave": "Rivière ardente vomie par le volcan ; refroidie, je deviens roche noire.",
  "Vapeur": "Je m’élève en soupirant et je meurs en perles sur les vitres froides.",
  "Poussière": "Je danse dans le rayon de lumière et m’endors sous les meubles oubliés.",
  "Fumée": "Pas de moi sans flamme, dit-on ; je grimpe en volutes grises et pique les yeux.",
  "Pierre": "Roulante, je n’amasse pas mousse ; on me jette parfois la première.",
  "Sable": "Je file entre tes doigts, je compte les heures, je bâtis des châteaux d’un jour.",
  "Cendre": "Ce qui reste quand la flamme a tout dévoré ; le phénix renaît de moi.",
  "Métal": "Froid au toucher, je tinte sous le marteau et j’attire la foudre.",
  "Verre": "Transparent mais têtu, je laisse passer le jour et me brise en mille éclats.",
  "Cristal": "Je tinte quand on trinque, et le flocon de neige est mon petit cousin.",
  "Magma": "Je bouillonne sous tes pieds en attendant que le volcan m’ouvre la porte.",
  "Argile": "Pétris-moi, tourne-moi, cuis-moi : je deviens bol, brique ou statuette.",
  "Charbon": "Noir trésor des mineurs, je finis dans la chaussette des enfants pas sages.",
  "Sel": "Je pique les plaies, je fais fondre le verglas et je relève ta soupe.",
  "Fer": "Ton sang me porte, la pluie me fait rougir ; bats-moi tant que je suis chaud !",
  "Cuivre": "Rose orangé, je file le courant et je verdis en vieillissant sur les toits.",
  "Or": "Le silence me vaut, dit-on ; les chercheurs de pépites me traquent au tamis.",
  "Argent": "Je ne fais pas le bonheur, dit-on, mais je fais fuir les loups-garous.",
  "Étain": "Plie-moi, je crie tout bas ; marie-moi au roux et naît l’âge du bronze.",
  "Bronze": "Médaille du troisième, je fais sonner les cloches et j’ai nommé tout un âge.",
  "Acier": "Lame, poutre ou ressort : je suis le muscle des gratte-ciel et le fil des épées.",
  "Plomb": "Gris et si lourd, je fais les petits soldats et les rêves des alchimistes.",
  "Calcaire": "Je tache de blanc ta bouilloire et je dresse les falaises d’Étretat.",
  "Marbre": "Froid et veiné, j’ai offert David à Michel-Ange. Rien ne m’émeut.",
  "Granite": "Moucheté gris et rose, je borde la côte bretonne et les cuisines chics.",
  "Obsidienne": "Noire et luisante, miroir de sorcière, je taillais les lames aztèques.",
  "Quartz": "Je bats la seconde au cœur des montres et je fleuris en pointes laiteuses.",
  "Diamant": "Je raye tout et rien ne me raye ; on dit que je suis éternel.",
  "Graphite": "Je suis l’âme grise de ton crayon, et la gomme est mon ennemie.",
  "Pétrole": "Or noir jaillissant du désert, je fais rouler le monde et pleurer les mouettes.",
  "Goudron": "Noir et collant, je tapisse les routes ; avec des plumes, je punis les bandits.",
  "Béton": "Gris et coulé, je fais les tours ; un alibi taillé en moi est inattaquable.",
  "Ciment": "Poudre grise, je durcis au contact de l’onde et je lie les briques entre elles.",
  "Plâtre": "Blanc comme un fantôme, je tiens ta jambe cassée et je lisse les murs.",
  "Céramique": "Terre cuite émaillée, je deviens tasse, carreau ou vase sous la main du potier.",
  "Porcelaine": "Si fine que le jour me traverse ; un éléphant chez moi, quelle catastrophe !",
  "Papier": "Lettre, avion ou cocotte pliée : j’enveloppe la roche, le ciseau me tranche.",
  "Encre": "Je fais couler les plumes et noircis les pages ; la seiche me crache pour fuir.",
  "Cire": "Les abeilles me bâtissent en hexagones ; je pleure au pied des chandelles.",
  "Caoutchouc": "Je rebondis, je m’étire, je gomme tes fautes et je chausse les voitures.",
  "Plastique": "Je suis partout, je dure des siècles ; les tortues me prennent pour des méduses.",
  "Laine": "Pelote pour les chats, pull qui gratte : la brebis me porte avant toi.",
  "Coton": "Doux flocon cueilli dans les champs, je deviens ton tee-shirt préféré.",
  "Tissu": "Trame et chaîne entrelacées, je deviens robe, drap ou rideau.",
  "Cuir": "Jadis peau, me voilà blouson de motard, ceinture ou botte qui craque.",
  "Corde": "Je tire les cloches, j’amarre les navires et je fais sauter les écoliers.",
  "Rouille": "Lèpre rousse des grilles oubliées, je ronge les clous et les vieux vélos.",
  "Pierre ponce": "Roche, je flotte pourtant, et je râpe la corne de tes talons.",
  "Compost": "Épluchures et vers de terre me fabriquent ; je rends au jardin ce qu’il a donné.",
  "Sédiment": "Grain à grain, je me dépose au fond des eaux et j’écris l’histoire en strates.",
  "Suie": "Je noircis les cheminées et les joues des ramoneurs.",
  "Résine": "Larme dorée des conifères, je colle aux doigts et parfume les pinèdes.",
  "Ambre": "Miel de pierre, je garde un moustique captif depuis l’ère des dinosaures.",
  "Soie": "Un ver m’a filée pour toi ; je glisse sur la peau et j’ai nommé une route.",
  "Colle": "En tube ou en pot, je tiens tout ensemble ; gare à tes doigts, je ne lâche rien.",
  "Contreplaqué": "Feuilles minces aux fibres croisées, je suis l’étagère qui ne gondole pas.",
  "Foin": "Chercher une aiguille en moi ? Bon courage ! Les vaches me croquent l’hiver.",
  "Silex": "Frappé, je crache des étincelles ; l’homme des cavernes m’a taillé en pointes.",
  "Ocre": "Jaune ou rouge, j’ai coloré les bisons de Lascaux et les villages du Roussillon.",

  # Phénomènes Naturels
  "Pollution": "Je noircis les poumons des cités et j’irise les rivières d’huile.",
  "Pluie": "Je tambourine aux carreaux ; les escargots sortent, les pique-niques rentrent.",
  "Nuage": "Mouton de coton qui broute le bleu ; vois-tu le dragon que je deviens ?",
  "Énergie": "Einstein m’a mise en équation ; rien ne se perd, je change de costume.",
  "Vent": "Invisible, je fais danser les blés, voler les chapeaux et tourner les moulins.",
  "Bourrasque": "Soudain coup d’épaule du ciel : ton parapluie se retourne en tulipe !",
  "Tempête": "Volets qui claquent, marins qui prient… parfois je tiens dans un verre d’eau.",
  "Éclair": "Zigzag aveuglant du ciel, ou chou fourré au café : je file en un instant.",
  "Tornade": "Entonnoir furieux, j’ai emporté Dorothée et son chien bien loin du Kansas.",
  "Explosion": "Boum ! En un instant tout vole en éclats ; il ne reste qu’un visage noirci.",
  "Incendie": "Sirènes hurlantes, grande échelle : les pompiers accourent pour m’éteindre.",
  "Brasier": "Ardent foyer qui rougeoie et crépite ; approche-toi, mais pas trop !",
  "Geyser": "Le sol gronde et crache un jet brûlant vers le ciel ; l’Islande m’a nommé.",
  "Vague": "Je roule, je déferle, je m’échoue ; les surfeurs guettent ma crête.",
  "Ozone": "Bouclier bleu tissé là-haut ; on s’inquiète d’un trou dans mon manteau.",
  "Lumière": "Je file à trois cent mille kilomètres par seconde et je fais fuir l’ombre.",
  "Arc-en-ciel": "Écharpe à sept couleurs après l’averse ; un lutin cache son or à mon pied.",
  "Temps": "Je file sans bruit ; on prétend me tuer, me perdre ou me gagner.",
  "Neige": "Je tombe en flocons muets ; les enfants me roulent en bonhomme à nez carotte.",
  "Glace": "Je tinte dans les verres, je porte les patineurs et je fonds en cornet.",
  "Blizzard": "Tourbillon blanc qui gifle et aveugle ; tu ne vois plus le bout de tes moufles.",
  "Tsunami": "Un mot japonais ; l’estran se vide, puis un mur liquide engloutit la côte.",
  "Déluge": "Quarante jours sans éclaircie ; Noé a bâti son arche pour me survivre.",
  "Brouillard": "Purée de pois sur Londres : tu n’y vois plus le bout de ton nez.",
  "Rosée": "Perles d’aube semées sur les prés ; le premier rayon me boit.",
  "Givre": "Je brode des fougères blanches sur les vitres et sucre les prés à l’aube.",
  "Grêle": "Billes blanches tombées du ciel : je cabosse les voitures et hache les vignes.",
  "Orage": "Après la lourdeur d’août, le ciel gronde et se zèbre ; compte les secondes !",
  "Ouragan": "On me donne un prénom, et mon œil reste calme quand tout tourne autour.",
  "Séisme": "Le sol frissonne, la vaisselle danse ; Richter me note sur son échelle.",
  "Érosion": "Patiente sculptrice, je ronge falaises et sommets grain après grain.",
  "Marée": "Deux fois par jour je m’en vais et reviens ; le Mont-Saint-Michel m’attend.",
  "Chaleur": "Je fais perler les fronts, onduler le bitume et fondre les sorbets.",
  "Froid": "Je rougis les nez, je fais claquer les dents et fumer les haleines.",
  "Sécheresse": "Le sol se fend en puzzle, les puits soupirent : pas une goutte depuis mai.",
  "Inondation": "Le fleuve sort de son lit et visite les salons ; on rame dans la rue.",
  "Avalanche": "Un cri de trop sur la pente, et tout le manteau blanc dévale en grondant.",
  "Glissement de terrain": "Après l’averse, le coteau lâche prise et dévale, emportant routes et maisons.",
  "Saison": "Nous sommes quatre sœurs qui se passent le relais ; Vivaldi nous a chantées.",
  "Jour": "Je commence au chant du coq et cède ma place quand les étoiles s’allument.",
  "Nuit": "Les hiboux veillent, tous les chats sont gris et les rêves prennent le relais.",
  "Ombre": "Je te suis partout sans bruit ; Peter Pan m’a perdue un soir.",
  "Son": "Je voyage jusqu’à tes oreilles ; dans le vide, nul ne m’entend.",
  "Écho": "Crie « Ohé ! » face au vide : je te le rends, un peu plus faible… faible…",
  "Feu de forêt": "Les pins crépitent en août ; les Canadair plongent dans la rade pour m’éteindre.",
  "Pluie acide": "Averse au goût de citron amer : je ronge les statues et roussis les sapins.",
  "Hiver": "Écharpes, moufles et chocolat chaud : les ours dorment pendant que je règne.",
  "Printemps": "Les bourgeons éclatent, les hirondelles reviennent et l’on change d’heure.",
  "Été": "Cigales, grandes vacances et glaces qui coulent sur les doigts.",
  "Automne": "Je roussis les bois, gonfle les champignons et ramène les cartables.",
  "Ciel": "Grand plafond bleu sans fin ; les oiseaux y nagent et les étoiles s’y piquent.",
  "Coucher de soleil": "L’astre du jour plonge à l’horizon et peint l’ouest d’orange et de rose.",
  "Verglas": "Patinoire invisible sur le bitume : à l’aube, les voitures valsent.",
  "Mirage": "Au loin, un lac miroite sur le sable… approche, et je m’évapore.",
  "Tonnerre": "Je roule après le zigzag céleste ; le capitaine Haddock m’invoque à Brest !",
  "Buée": "Souffle sur la vitre : j’apparais, et tu peux y dessiner un cœur.",
  "Feu follet": "Petite flamme bleue qui danse sur la tourbière ; ne la suis pas la nuit !",

  # Physique
  "Atome": "Les Grecs me croyaient insécable ; on m’a pourtant coupé, et ça a fait boum.",
  "Électron": "Minuscule et négatif, je tourne en nuage et je cours dans tes câbles.",
  "Proton": "Positif de nature, je trône au cœur de la matière et donne son numéro à chacun.",
  "Neutron": "Ni plus ni moins, je dors au cœur de la matière et brise l’uranium.",
  "Noyau atomique": "Cœur dense et minuscule au milieu d’un immense vide ; me briser libère l’enfer.",
  "Particule": "Les nobles me portent devant leur nom ; sous Genève, on me fait percuter.",
  "Onde": "Je pars en cercles du caillou jeté et je file sans rien emporter.",
  "Magnétisme": "Force invisible, je fais danser les aurores et pointer l’aiguille vers le nord.",
  "Aimant": "Je retiens tes dessins sur le frigo ; deux de mes pôles pareils se fuient.",
  "Électricité": "Je cours dans les fils, j’allume tes lampes et je picote les doigts curieux.",
  "Pression": "Je bouche tes oreilles en plongée et je fais siffler la cocotte-minute.",
  "Gravité": "Newton m’a reçue sur la tête ; c’est moi qui te ramène au sol après chaque saut.",
  "Masse": "Sur la Lune tu pèses moins, mais moi je ne change pas d’un gramme.",
  "Force": "Pousse, tire, soulève… Que je sois avec toi, jeune padawan !",
  "Mouvement": "Rien ne tient en place quand je passe : la feuille tombe, le cœur bat, tu cours.",
  "Vitesse": "Les radars me guettent et le guépard me porte comme une médaille.",
  "Friction": "Frotte tes mains l’hiver : je les réchauffe et j’use tes semelles.",
  "Plasma": "Quatrième état de la matière, je brille dans les néons et les aurores.",
  "Radiation": "Je rayonne en tous sens, invisible ; le trèfle jaune et noir te met en garde.",
  "Radioactivité": "Marie Curie m’a apprivoisée ; certains cailloux crépitent sous le Geiger.",
  "Fusion nucléaire": "Deux cœurs minuscules s’unissent, et le Soleil brille : c’est mon secret.",
  "Fission nucléaire": "Je casse l’uranium en deux, et les centrales en tirent leur courant.",
  "Lentille": "Bombée comme une petite graine, je grossis la fourmi sous l’œil du curieux.",
  "Prisme": "Un rayon blanc entre par ma face, il sort en sept couleurs ; Pink Floyd m’adore.",
  "Spectre lumineux": "Du rouge au violet, toutes les couleurs rangées en ruban, comme un éventail.",
  "Infrarouge": "Invisible à tes yeux, je trahis les corps tièdes aux lunettes de nuit.",
  "Ultraviolet": "Je dore ta peau et la brûle si tu oublies ta crème ; les abeilles me voient.",
  "Rayons X": "Je traverse ta chair et montre tes os au docteur ; Superman voit grâce à moi.",
  "Vide": "Rien, absolument rien : l’espace entre les astres, ou ton frigo un lundi soir.",
  "Gaz": "Sans forme, je remplis tout le flacon et m’échappe dès qu’on l’ouvre.",
  "Liquide": "Je prends la forme du verre qui m’accueille et je coule entre tes doigts.",
  "Solide": "Je garde ma forme quoi qu’il arrive ; tu peux t’asseoir sur moi sans couler.",
  "Température": "Le mercure me raconte ; quand je grimpe à 39, tu files sous la couette.",
  "Inertie": "Le bus freine, et tu continues tout seul vers l’avant : c’est encore moi.",
  "Relativité": "E = mc², c’est ma signature ; Einstein m’a fait courber l’espace.",
  "Physique quantique": "Un chat à la fois mort et vivant dans sa boîte : bienvenue chez moi.",
  "Antimatière": "Reflet inversé de tout ; si je touche mon jumeau, pouf, un éclair de clarté !",
  "Électricité statique": "Je dresse tes cheveux sur ta tête et je te pique quand tu touches la poignée.",
  "Bulle de savon": "Sphère irisée qu’un souffle libère ; elle danse, elle brille, et pop !",

  # Chimie
  "Hydrogène": "Le plus léger de tous, premier de la liste ; le Hindenburg s’en souvient encore.",
  "Oxygène": "Tu me prends à chaque inspiration ; sans moi, nulle flamme ne danse.",
  "Carbone": "Mine de crayon ou bague de fiançailles : c’est toujours moi, en habit différent.",
  "Azote": "Quatre bouffées sur cinq de ton souffle, c’est moi, discret et paresseux.",
  "Hélium": "Une bouffée de moi, et ta voix devient celle d’un canard de dessin animé !",
  "Sodium": "Métal si mou qu’on le coupe au couteau ; jeté dans l’eau, je pique une colère.",
  "Chlore": "L’odeur des piscines, c’est moi : je chasse les microbes et rougis tes yeux.",
  "Calcium": "Je bâtis tes dents et ton squelette ; un grand verre blanc au goûter me livre.",
  "Silicium": "Ma vallée californienne pense pour le monde entier, puce après puce.",
  "Soufre": "Jaune vif, je sens l’œuf pourri, et l’on dit que le diable m’adore.",
  "Phosphore": "Je luis tout seul dans le noir et je dors au bout de chaque allumette.",
  "Molécule": "Bande de copains liés pour la vie ; H₂O est la plus célèbre d’entre nous.",
  "Réaction chimique": "Ça mousse, ça fume, ça change de couleur : la matière fait peau neuve !",
  "Combustion": "Tout ce qui brûle passe entre mes mains et finit en cendres et en volutes.",
  "Oxydation": "Rouille sur le vélo, chair brunie du fruit croqué : c’est mon œuvre lente.",
  "Acide": "Je pince la langue comme un citron et je ronge le marbre sans pitié.",
  "Base chimique": "Je glisse sous les doigts et je bleuis le tournesol ; l’acide me fuit.",
  "Dioxyde de carbone": "Je pétille dans ta limonade et je réchauffe un peu trop la planète.",
  "Méthane": "Les rots des ruminants me libèrent ; je danse en flamme bleue sous la casserole.",
  "Ammoniac": "Mon odeur te pique le nez dans les litières et les produits ménagers.",
  "Eau salée": "Les larmes et l’océan ont mon goût ; je pique les yeux du nageur.",
  "Solution": "Le grain blanc fond dans ton thé et nage en moi. Je suis aussi la réponse !",
  "Distillation": "Mon alambic chauffe, la buée s’élève puis retombe goutte à goutte, pure.",
  "Cristallisation": "Laisse dormir le bocal : des géométries scintillantes y poussent en silence.",
  "Catalyseur": "Je presse les autres de changer et je ressors intact, tel un entremetteur.",
  "Alcool": "Je réchauffe les fêtes, fais tourner les têtes et nettoie les plaies en piquant.",
  "Sucre": "Les dentistes me craignent, les fourmis me suivent, ton café me réclame.",
  "Amidon": "Je rends la pomme de terre farineuse et la chemise raide sous le fer.",
  "Savon": "Je glisse des mains, je mousse et je fais fuir les microbes en chantant.",
  "Vinaigre": "Je pique la salade, je fais grimacer et j’adore les cornichons.",
  "Engrais": "Je fais grossir les citrouilles ; le jardinier me sème au pied des rosiers.",
  "Poudre à canon": "Noire, venue de Chine, je fais tonner les mousquets et fleurir les fusées.",
  "Polymère": "Une chaîne de mille maillons identiques : nylon, caoutchouc, bouteille…",
  "Tableau périodique": "Mendeleïev m’a rangé en cases ; chaque élément y a sa place, même les absents.",
  "Laboratoire": "Blouses blanches, fioles fumantes et éprouvettes : voici l’antre du savant.",

  # Formations Naturelles
  "Montagne": "Les alpinistes grimpent jusqu’à mon sommet pour y planter leur drapeau.",
  "Volcan": "J’ai enseveli Pompéi ; à mon réveil, je crache des fleuves rougeoyants.",
  "Lac": "Miroir tranquille entre les monts ; Nessie se cacherait dans l’un de nous.",
  "Océan": "Pacifique ou Atlantique, je couvre presque tout le globe de mon bleu infini.",
  "Continent": "Afrique, Asie, Europe… je suis l’une des grandes pièces du puzzle du globe.",
  "Planète Terre": "Grosse bille bleue, je suis ta maison, la troisième en partant de l’astre roi.",
  "Île": "Robinson y a échoué ; je suis un bout de sol cerné de vagues de tous côtés.",
  "Désert": "Mirages, chameaux et soif : le Petit Prince y a rencontré un aviateur.",
  "Oasis": "Mirage devenu vrai : des dattiers et de quoi boire au milieu des sables.",
  "Marais": "Shrek y vit heureux, entre roseaux, grenouilles et brume stagnante.",
  "Forêt": "Le Petit Chaperon rouge s’y est égaré ; le loup y rôde entre les troncs.",
  "Jungle": "Mowgli y a grandi parmi les lianes, Baloo et les rugissements de Shere Khan.",
  "Récif": "Nemo et ses amis vivent dans mes ruelles colorées, sous les flots tièdes.",
  "Jardin": "Candide conseillait de le cultiver ; on y bêche, on y sème, on y rêve.",
  "Rivière": "Je serpente vers la mer en chantant sur mes galets ; les truites me remontent.",
  "Cascade": "Je me jette du haut des rochers en rugissant ; Niagara est ma reine.",
  "Plage": "Serviettes, parasols et châteaux qui s’écroulent : c’est ici qu’on bronze.",
  "Falaise": "Étretat a ses aiguilles ; moi, je tombe à pic dans les flots, blanche ou ocre.",
  "Grotte": "Lascaux cache ses bisons peints dans mon ventre sombre et frais.",
  "Canyon": "Gorge immense d’Arizona, j’ai été taillé au couteau par le Colorado.",
  "Vallée": "Creux verdoyant entre deux crêtes, j’accueille villages et troupeaux.",
  "Colline": "Petite bosse herbeuse ; Rome en a sept, et les moutons m’adorent.",
  "Glacier": "Fleuve gelé qui avance d’un pas de tortue ; le climat me fait fondre.",
  "Iceberg": "Le Titanic n’a vu que ma pointe ; le reste dormait sous les flots.",
  "Banquise": "Plancher blanc où l’ours polaire chasse le phoque ; je fonds un peu chaque été.",
  "Delta": "Comme la lettre grecque, le Nil s’ouvre en triangle avant d’embrasser les flots.",
  "Plaine": "Tout est plat à perte de vue ; les blés ondulent jusqu’à l’horizon.",
  "Prairie": "La petite maison de Laura s’y dressait, parmi les foins et les coquelicots.",
  "Savane": "Lions, girafes et acacias : c’est ici que le Roi Lion a vu le jour.",
  "Toundra": "Sol gelé sans un seul arbre, où les caribous broutent sous le vent arctique.",
  "Mer": "Méditerranée ou Baltique : je berce les bateaux et lèche chaque côte.",
  "Source": "Je jaillis fraîche d’entre les rochers : chaque fleuve commence par moi.",
  "Atoll": "Anneau de sable blanc autour d’un lagon turquoise, perdu dans le Pacifique.",
  "Stalactite": "Je pends du plafond des cavernes, goutte après goutte ; ma sœur pousse en bas.",
  "Sol fertile": "Noir, riche et grouillant de vers, je fais germer tout ce qu’on me confie.",
  "Tourbe": "On me brûle en Irlande et je parfume le whisky écossais de fumée.",
  "Fossile": "Empreinte figée dans la roche, je raconte des bêtes disparues depuis des éons.",
  "Pôle": "Toutes les boussoles me montrent du doigt ; le Père Noël habite au Nord.",
  "Source hydrothermale": "Cheminée brûlante des abysses, je nourris crabes et vers géants sans soleil.",
  "Volcan de boue": "Je fais des bulles de glaise tiède en gargouillant ; on s’y baigne en Colombie.",
  "Désert de sel": "Immense miroir blanc et craquelé ; au Salar d’Uyuni, le ciel se reflète.",
  "Archipel": "Chapelet de terres semées sur les flots, comme Hawaï ou les Cyclades.",
  "Fjord": "Long doigt salé entre les parois norvégiennes, où voguaient les Vikings.",
  "Taïga": "Immense manteau de conifères en Sibérie, où rôdent l’ours et le tigre.",
  "Dune": "Bosse dorée qui voyage au gré du souffle ; Frank Herbert m’a offert un roman.",

  # Cosmos
  "Étoile": "Les bergers me comptent, les marins me suivent ; je cligne sans jamais dormir.",
  "Aurore": "Voilage vert et rose qui ondule en silence au-dessus des rennes et des igloos.",
  "Météore": "Caillou céleste qui s’embrase en tombant ; fais vite un vœu avant que je meure !",
  "Galaxie": "Spirale géante de cent milliards de soleils ; Andromède est ma voisine.",
  "Univers": "Tout ce qui existe tient en moi, et je grandis encore sans fin connue.",
  "Soleil": "Louis XIV se prenait pour moi ; regarde-moi en face et tu pleureras.",
  "Lune": "Je change de visage chaque soir, et Armstrong a marché sur ma joue grise.",
  "Planète": "Vagabonde, disaient les Grecs : je tourne autour d’un astre sans briller seule.",
  "Comète": "Boule de neige sale, je traîne une chevelure brillante ; Halley me guettait.",
  "Astéroïde": "Rocher errant entre Mars et Jupiter ; l’un de nous a éteint les dinosaures.",
  "Nébuleuse": "Brume cosmique aux couleurs de bonbon, je suis la pouponnière des astres.",
  "Supernova": "Un astre meurt en feu d’artifice et brille soudain plus que tous ses frères.",
  "Trou noir": "Gouffre glouton : même la lumière ne s’échappe pas de mon ventre.",
  "Constellation": "Relie les points brillants et tu verras une Grande Ourse ou un Scorpion.",
  "Éclipse": "En plein midi, le jour s’éteint : un disque sombre mord l’astre d’or.",
  "Orbite": "Ronde éternelle, je suis le chemin invisible qu’un astre suit autour d’un autre.",
  "Big Bang": "Il y a 13,8 milliards d’années, tout a commencé par moi… sans aucun bruit.",
  "Poussière d'étoiles": "Selon Carl Sagan, tu es fait de moi : grains semés par des astres morts.",
  "Système solaire": "Huit mondes et un astre roi au centre : c’est ton quartier dans la galaxie.",
  "Voie lactée": "Écharpe pâle qui barre le ciel d’été ; Héra y aurait renversé son biberon.",
  "Mars": "Rouge comme la guerre dont je porte le nom ; des robots roulent sur mon sol.",
  "Jupiter": "Géant rayé, j’ai un œil rouge où souffle un ouragan depuis des siècles.",
  "Saturne": "Mon tutu de glaçons et de cailloux fait de moi le plus coquet des géants.",
  "Anneaux planétaires": "Hula-hoop céleste fait de milliards de glaçons qui tournent autour d’un géant.",
  "Pulsar": "Phare cosmique, je clignote si régulièrement qu’on m’a cru un signal d’aliens.",
  "Quasar": "Je suis le phare le plus éclatant des confins, allumé par un gouffre glouton.",
  "Matière noire": "Invisible, je pèse pourtant plus que tout le reste ; les savants me traquent.",
  "Espace": "Chez moi, personne ne t’entend crier, et les astronautes flottent sans poids.",
  "Cratère": "Cicatrice ronde d’un caillou tombé du ciel ; Séléné en a le visage criblé.",
  "Marée lunaire": "Deux fois par jour, l’astre des nuits tire la mer par la manche, puis la lâche.",

  # Flore
  "Plante": "Verte et immobile, je bois par les pieds et je tends mes bras vers le ciel.",
  "Arbre": "Les oiseaux nichent dans mes bras ; compte mes cernes pour savoir mon âge.",
  "Herbe": "Je chatouille tes pieds nus en mai ; le mouton m’adore, la tondeuse aussi.",
  "Fleur": "L’abeille me butine, l’amoureux m’offre ; hélas, je fane bien trop vite.",
  "Rose": "Reine des parterres, je pique qui me cueille ; rouge, je dis « je t’aime ».",
  "Cactus": "Je garde ma gourde sous ma peau hérissée ; surtout, ne me fais pas de câlin !",
  "Bambou": "Le panda me croque sans fin ; creux et noueux, je grandis d’un mètre par jour.",
  "Blé": "Mes épis dorés ondulent sous la brise ; moulu, je deviens farine puis pain.",
  "Riz": "Grains blancs cueillis les pieds mouillés en Asie, on me lance aux mariés.",
  "Maïs": "Mon épi jaune éclate en pop-corn dans la poêle ; les Aztèques me vénéraient.",
  "Vigne": "Tordue sur les coteaux, je tends mes grappes au vendangeur de septembre.",
  "Raisin": "Pressé, je deviens vin ; le renard de La Fontaine me trouvait trop vert.",
  "Pomme": "Croquée par Ève, tombée sur Newton, empoisonnée pour Blanche-Neige.",
  "Olive": "Verte ou noire, je pique l’apéritif ; pressée, je dore la cuisine du Sud.",
  "Légume": "Carotte, poireau ou navet : « Mange-les, dit maman, et tu grandiras ! »",
  "Pomme de terre": "Frite, purée ou chips, je suis le tubercule que Parmentier rendit célèbre.",
  "Tournesol": "Van Gogh m’a peint en bouquet ; je tourne la tête pour suivre l’astre du jour.",
  "Chêne": "Saint Louis rendait justice à mon ombre ; mes glands régalent les sangliers.",
  "Sapin": "En décembre, on m’habille de guirlandes et on glisse des cadeaux à mes pieds.",
  "Palmier": "Tout en haut de mon long tronc écailleux, je berce dattes ou cocos.",
  "Lierre": "Je grimpe aux vieilles façades et m’y accroche ; toujours vert, jamais pressé.",
  "Mousse": "Tapis velouté du sous-bois, je pousse du côté nord des troncs, dit-on.",
  "Fougère": "Mes crosses se déroulent en volutes ; les dinosaures broutaient mes aïeules.",
  "Champignon": "Je sors après l’averse, chapeau sur la tête ; Mario grandit en me mangeant.",
  "Algue": "Je danse au fond des flots ; les Japonais m’enroulent autour de leurs makis.",
  "Graine": "Toute petite promesse endormie : enfouis-moi, et je deviendrai géante.",
  "Fruit": "Juteux et sucré, je pends aux branches ; cinq par jour, conseille le docteur.",
  "Pollen": "Poudre d’or qui colle aux pattes des butineuses et fait éternuer en avril.",
  "Feuille": "Verte en avril, rousse en octobre, je tourbillonne avant de tomber.",
  "Racine": "Cachée sous tes pas, je bois et j’ancre ; un poète tragique porte mon nom.",
  "Bois": "Je craque dans la cheminée, je flotte sur l’étang, et Pinocchio en est fait.",
  "Cotonnier": "Mes capsules éclatent en flocons blancs que l’on file pour tisser tes t-shirts.",
  "Lin": "Mes petites corolles bleues deviennent draps frais et nappes de grand-mère.",
  "Thé": "Infusé à cinq heures chez les Anglais, je me sirote avec un nuage de lait.",
  "Café": "Noir et fumant, je chasse le sommeil du matin ; Balzac m’en buvait des litres.",
  "Cacao": "Les Mayas me buvaient amer ; torréfié et sucré, je deviens ta tablette.",
  "Canne à sucre": "Haute tige des Antilles, on me broie pour mon jus doux et pour le rhum.",
  "Herbe médicinale": "Camomille ou sauge, la guérisseuse me cueille pour apaiser tes maux.",
  "Lichen": "Les rennes me broutent sous les frimas ; je peins les rochers de croûtes dorées.",
  "Nénuphar": "Monet m’a peint cent fois ; la grenouille se repose sur mon radeau flottant.",
  "Tomate": "Rouge et juteuse, je finis en ketchup ou en sauce sur tes spaghettis.",
  "Laitue": "Verte et croquante, je garnis ton sandwich ; les escargots raffolent de moi.",
  "Noix de coco": "Coque poilue tombée de très haut, je cache un lait frais dans ma boule.",
  "Érable": "Ma feuille flotte sur le drapeau canadien ; mon sirop nappe tes crêpes.",
  "Bouquet": "Lancé par la jeune épouse, je promets des noces à qui m’attrape au vol.",
  "Citrouille": "À Halloween, on me creuse un sourire ; pour Cendrillon, je deviens carrosse.",

  # Biologie
  "Vie": "Je bats dans chaque cœur, du premier cri jusqu’au dernier souffle.",
  "Cellule": "Brique minuscule de ton corps, je me divise en deux pour me multiplier.",
  "ADN": "Double hélice enroulée, je suis le mode d’emploi secret de chaque être.",
  "Gène": "Petit bout de ton code, c’est moi qui t’ai donné les yeux de ta mère.",
  "Bactérie": "Invisible, je fais le yaourt ou la fièvre ; les antibiotiques me traquent.",
  "Virus": "Je te refile le rhume, et j’infecte même les ordinateurs !",
  "Plancton": "Poussière vivante dérivant dans les flots, je suis le festin de la baleine.",
  "Protéine": "Les culturistes m’avalent en shaker ; je bâtis tes muscles brique par brique.",
  "Enzyme": "Ciseaux minuscules de ta salive, je découpe ton repas pour le digérer.",
  "Photosynthèse": "Cuisine verte : la feuille boit les rayons et souffle l’air que tu respires.",
  "Chlorophylle": "Pigment discret, je verdis les prés et je capture les rayons de l’astre.",
  "Évolution": "Darwin m’a lue dans le bec des pinsons : seuls les mieux adaptés survivent.",
  "Mutation": "Une coquille dans ton code, et voilà les X-Men ou un mouton à cinq pattes !",
  "Symbiose": "Le poisson-clown et l’anémone ? Je suis leur pacte de bons colocataires.",
  "Écosystème": "Toile invisible où chaque être, du ver au loup, dépend de tous ses voisins.",
  "Chaîne alimentaire": "Le criquet finit dans la souris, la souris dans la buse : qui mange qui ?",
  "Décomposition": "Je change les dépouilles en humus : rien ne se perd, tout se transforme.",
  "Fermentation": "Patiente cuisine des microbes, je fais pétiller le cidre et mûrir le fromage.",
  "Levure": "Petite bête invisible, je fais gonfler la pâte à pain et mousser la bière.",
  "Microbe": "Pasteur m’a traqué sans relâche ; lave-toi les mains pour me chasser !",
  "Organisme": "Microbe, chêne ou baleine : tout être vivant, si petit soit-il, en est un.",
  "Reproduction": "La cigogne n’y est pour rien : c’est moi qui fais naître les petits !",
  "Œuf": "Suis-je venu avant la cocotte ? En attendant, on me casse pour l’omelette.",
  "Embryon": "Je flotte, recroquevillé, et deviens bébé en neuf mois de patience.",
  "Métamorphose": "Gregor Samsa s’est réveillé insecte par ma faute ; le têtard me connaît bien.",
  "Instinct": "Nul n’apprend au saumon à remonter la rivière : je lui souffle le chemin.",
  "Espèce": "Homo sapiens est la tienne ; Darwin a raconté leur origine en 1859.",
  "Extinction": "Disparus à jamais, comme le dodo : je suis la dernière page d’une lignée.",
  "Biodiversité": "Mille formes, mille couleurs : je suis la richesse foisonnante du vivant.",
  "Parasite": "Je loge chez toi sans payer et me nourris à tes dépens, comme le pou.",
  "Pollinisation": "Poudre d’or portée de corolle en corolle par les butineuses : voilà mon œuvre.",
  "Respiration": "Gonfle, dégonfle… je suis le va-et-vient tranquille de tes poumons.",

  # Vie et Créatures
  "Lombric": "Laboureur sans charrue, je digère la terre et sors après l’averse.",
  "Asticot": "Petit ver blanc grouillant, je serai mouche ; en attendant, j’appâte.",
  "Chenille": "Goinfre aux mille petites pattes, je m’endors en cocon pour renaître ailée.",
  "Papillon": "Fleur qui vole : un battement de mes ailes, dit-on, lève une tempête au loin.",
  "Poisson": "Muet, dit-on, comme moi ; et le 1er avril, on m’accroche dans ton dos !",
  "Poisson Tropical": "Rayé d’orange comme Nemo, je nage en couleurs dans les mers chaudes.",
  "Poisson Polaire": "Un antigel dans les veines, je nage sous la mer figée de l’Arctique.",
  "Poisson Volant": "Mes nageoires se font ailes : je bondis hors des flots et plane au loin.",
  "Poisson Abyssal": "Dans le noir des grands fonds, ma lanterne frontale attire les proies.",
  "Méduse": "Ombrelle de gelée transparente, je pique les baigneurs distraits.",
  "Salamandre": "Noire et jaune, on me crut née des flammes ; François Ier me prit pour emblème.",
  "Ptérodactyle": "Reptile aux ailes de cuir, je planais au-dessus des tyrannosaures.",
  "Luciole": "Petite lanterne volante, j’allume les soirs d’été d’étincelles vertes.",
  "Oiseau": "Héritier des grands reptiles, je chante à l’aube perché sur une branche.",
  "Insecte": "Six pattes, deux antennes, trois parties : nous sommes des millions d’espèces.",
  "Abeille": "Rayée et butineuse, je danse pour dire à mes sœurs où trouver le nectar.",
  "Fourmi": "Peu prêteuse, j’ai laissé la cigale danser tout l’hiver le ventre vide.",
  "Araignée": "Sur mes huit pattes, je tisse un piège de dentelle et j’attends la mouche.",
  "Escargot": "Ma maison sur le dos, je laisse un ruban d’argent derrière moi après l’averse.",
  "Grenouille": "Embrasse-moi, et peut-être deviendrai-je un prince charmant !",
  "Serpent": "Sans pattes, je siffle et ondule ; au jardin d’Éden, j’ai offert la pomme.",
  "Lézard": "Je fais le paresseux sur les murets chauds et laisse ma queue au chat.",
  "Tortue": "Rien ne sert de courir : j’ai battu le lièvre, carapace et tout.",
  "Crocodile": "Mes larmes sont fausses ; j’ai croqué la main du capitaine Crochet.",
  "Dinosaure": "Un astéroïde a mis fin à mon règne ; Jurassic Park m’a ressuscité.",
  "Aigle": "Œil perçant et serres d’or, je plane au-dessus des cimes enneigées.",
  "Hibou": "Grands yeux ronds et aigrettes, je hulule quand tout le monde dort.",
  "Pingouin": "On me confond avec mon cousin du Sud, mais moi, je vole dans l’Atlantique Nord !",
  "Manchot": "En frac, je glisse sur le ventre en Antarctique ; voler ? Jamais appris.",
  "Poule": "Je caquette et je picore ; dans la fable, je pondais même de l’or !",
  "Mammifère": "Sang chaud, poils et mamelles : de la souris à la baleine, et toi aussi !",
  "Souris": "Quand le chat n’est pas là, je danse ; Mickey est mon plus célèbre cousin.",
  "Chat": "Je ronronne, j’ai neuf vies et je retombe toujours sur mes pattes.",
  "Chien": "Meilleur ami de l’homme, je remue la queue et je rapporte la balle.",
  "Loup": "J’ai mangé mère-grand, soufflé des maisons, et je hurle sous l’astre rond.",
  "Cheval": "Je hennis, je galope, et Troie m’a ouvert ses portes, ventre plein de soldats.",
  "Vache": "Je rumine au pré en regardant passer les trains, ma cloche au cou.",
  "Mouton": "On me compte pour s’endormir, et je suis le troupeau comme chez Panurge.",
  "Cochon": "Tout est bon chez moi, dit-on : groin rose et queue en tire-bouchon.",
  "Ours": "Je dors tout l’hiver au fond de ma tanière, et Baloo chante en mon nom.",
  "Ours polaire": "Géant blanc de l’Arctique, je guette le phoque au bord de la mer gelée.",
  "Baleine": "Géante qui chante, j’ai avalé Jonas et Pinocchio, puis j’ai soufflé un geyser.",
  "Dauphin": "Je saute en riant près des étraves ; en France, j’étais l’héritier du trône.",
  "Requin": "Mon aileron fend la surface : ta-dam, ta-dam… sors vite du bain !",
  "Pieuvre": "Huit bras, trois cœurs, et je crache un nuage noir pour filer en douce.",
  "Crabe": "Je marche de travers, pinces en avant, entre les rochers à marée basse.",
  "Corail": "Ni pierre ni plante, je suis animal et je bâtis des cités sous-marines.",
  "Chauve-souris": "Je dors la tête en bas, et Batman a emprunté ma silhouette.",
  "Singe": "Je me balance de liane en liane, banane en main, presque ton cousin.",
  "Éléphant": "Ma trompe me sert de bras, de douche et de trompette.",
  "Lion": "Crinière en couronne, je rugis sur la brousse ; Simba, c’est mon petit.",
  "Chameau": "Deux bosses de réserve, je traverse les dunes sans boire pendant des jours.",
  "Castor": "Mes dents orange abattent les troncs et ma queue plate claque sur l’onde.",
  "Moustique": "Bzzz à ton oreille, je pique et je file : à toi les démangeaisons !",
  "Plume": "Je bourre l’oreiller et, trempée d’encre, j’écrivais jadis les poèmes.",
  "Nid": "Petite coupe de brindilles tressée au creux d’une branche pour couver.",
  "Ruche": "Cité bourdonnante aux alvéoles hexagonales, une reine y règne.",
  "Toile d'araignée": "Dentelle tendue entre deux branches, où la mouche se prend sans repartir.",
  "Fourrure": "Manteau de poils doux, je tiens chaud à l’ours sans passer chez le tailleur.",
  "Écaille": "Petite tuile brillante, je couvre le serpent comme un toit d’ardoises.",
  "Os": "Charpente blanche cachée sous ta chair, le chien m’enterre au jardin.",
  "Mammouth": "Toison rousse et défenses courbes, les hommes des cavernes me peignaient.",
  "Oiseau marin": "Mouette ou goéland, je crie au-dessus des ports et chipe ton sandwich.",
  "Cygne": "Vilain petit canard devenu beauté blanche, je danse dans un ballet célèbre.",
  "Chèvre": "Monsieur Seguin m’a perdue face au loup ; tiens-moi par la barbichette !",
  "Cerf": "Je brame en automne et ma couronne de bois tombe chaque année.",
  "Canard": "Coin-coin ! Donald a mon bec, et mon cousin en plastique flotte dans ton bain.",
  "Zèbre": "Rayé noir sur blanc, ou blanc sur noir ? Les lions n’ont jamais tranché.",
  "Tigre": "Rayures orange et noires, je rôde en Inde ; Shere Khan, c’est moi.",
  "Phoque": "Gros yeux tendres et moustaches, je me dandine sur le ventre et j’aboie.",
  "Perroquet": "Plumage de mille couleurs, je répète tes mots, même les gros !",
  "Coquillage": "Colle-moi à ton oreille : tu entendras le ressac chanter.",
  "Hérisson": "Mille épines sur le dos, je me roule en boule quand on m’embête.",
  "Écureuil": "Queue en panache roux, je cache des noisettes et j’oublie où.",
  "Scorpion": "Pinces en avant et dard levé, je brille sous la lumière noire.",
  "Corbeau": "Perché, j’ai lâché mon festin au renard flatteur ; je croasse en noir.",
  "Grillon": "Je stridule au coin de l’âtre ; chez Pinocchio, j’étais la conscience.",
  "Cafard": "Je file sous l’évier quand tu allumes ; et quand tu broies du noir, c’est moi !",
  "Dodo": "Gros et incapable de voler, j’ai disparu de Maurice ; mon nom fait bâiller.",
  "Poussin": "Petite boule de duvet jaune, je pépie derrière ma mère qui caquette.",
  "Girafe": "Mon cou interminable me laisse brouter les cimes ; ma langue est bleue.",
  "Étoile de mer": "Cinq bras en astre sur le sable, je repousse si l’on m’en coupe un.",
  "Renard": "Roux et rusé, j’ai flatté le corbeau ; le Petit Prince m’a apprivoisé.",
  "Cigale": "Ayant chanté toute la belle saison, je fus fort dépourvue à la bise venue.",

  # Corps et Esprit
  "Sang": "Rivière rouge, je circule en toi sans repos ; les vampires me boivent.",
  "Cœur": "Je bats la mesure dans ta poitrine ; on me brise, on me donne, on me dessine.",
  "Cerveau": "Noix plissée sous ton crâne, je pilote tout, même tes songes.",
  "Œil": "Je cligne, je regarde, je pleure ; on me dit fenêtre de l’âme.",
  "Muscle": "Gonfle le biceps : je roule sous ta peau, et la salle de sport m’adore.",
  "Squelette": "Charpente blanche cachée sous ta chair, je claque des dents à Halloween.",
  "Neurone": "Je tends mes dendrites et passe l’influx nerveux de synapse en synapse.",
  "Pensée": "Fleur violette ou voix intérieure, je trotte dans ta tête sans dire un mot.",
  "Mémoire": "Coffre à souvenirs, je flanche parfois ; l’éléphant, dit-on, ne me perd jamais.",
  "Rêve": "Paupières closes, je t’emmène voler sans ailes ; au réveil, je m’effiloche.",
  "Sommeil": "Morphée m’ouvre ses bras ; je ferme tes paupières jusqu’au matin.",
  "Émotion": "Je serre ta gorge, te fais rougir ou pleurer ; Vice-Versa m’a mise en couleurs.",
  "Peur": "Je glace ton dos et fais claquer tes dents ; le monstre sous le lit me nourrit.",
  "Joie": "Je pétille, je saute, je danse ; Beethoven m’a écrit une ode.",
  "Tristesse": "Spleen de Baudelaire, blues du dimanche soir : je mouille tes yeux.",
  "Colère": "Je te fais voir rouge, serrer les poings et claquer les portes !",
  "Amour": "Cupidon décoche ses flèches pour moi ; on dit que je rends aveugle.",
  "Naissance": "Premier cri, premier souffle : neuf mois d’attente, et la cigogne arrive !",
  "Enfant": "Je grandis trop vite, je pose mille « pourquoi » et j’ai les genoux écorchés.",
  "Famille": "Parents, cousins, mamie… un arbre aux mêmes racines ; on ne nous choisit pas.",
  "Vieillesse": "Cheveux d’argent, rides de sourire : je viens à pas lents, canne à la main.",
  "Maladie": "Fièvre, toux et teint pâle : je t’envoie au lit sous la couverture.",
  "Santé": "On me souhaite en trinquant ; mieux vaut moi que richesse, dit le proverbe.",
  "Remède": "Tisane, sirop ou cataplasme, je soigne… quand je ne suis pas pire que le mal.",
  "Mort": "Faux à la main, capuche noire, je viens pour tous ; même les rois me cèdent.",
  "Tombe": "Dalle fleurie de chrysanthèmes, je porte un nom et deux dates gravés.",
  "Deuil": "Voile noir et cœur lourd, je dure longtemps après l’adieu.",
  "Langage": "À Babel, on m’a brouillé ; je tisse des phrases avec des mots.",
  "Conscience": "Petite voix intérieure, je te souffle le bien ; Jiminy Cricket m’incarne.",
  "Idée": "Eurêka ! Je jaillis d’un coup, et Archimède bondit tout nu de son bain.",
  "Curiosité": "Vilain défaut, dit-on ; Pandore m’écouta et souleva le couvercle.",
  "Courage": "Je ne t’empêche pas de trembler : je t’aide à avancer quand même.",
  "Sagesse": "Salomon me préféra à l’or ; ma dent pousse tard au fond de ta bouche.",
  "Faim": "Ton ventre gargouille quand je viens ; on me dit parfois de loup.",
  "Douleur": "Aïe ! Je pique, je lance, je brûle, et te fais sautiller sur un pied.",
  "Larme": "Perle salée, je roule sur ta joue au cinéma ou en coupant l’oignon.",
  "Rire": "Les chatouilles me déclenchent ; je te tords le ventre et je suis contagieux !",
  "Cauchemar": "Tu t’éveilles en sueur, le monstre aux trousses : je hante tes yeux clos.",
  "Sueur": "Je perle sur ton front après l’effort ; tu gagnes ton pain grâce à moi.",
  "Fatigue": "Paupières lourdes, bâillements en série : je réclame un bon oreiller.",
  "Pansement": "Je me pose sur ton genou écorché ; un bisou et moi, ça répare tout.",
  "Rhume": "Nez qui coule, mouchoirs en pile : je fais éternuer tout l’hiver. Atchoum !",

  # Créations Humaines
  "Aquarium": "Petit océan en boîte, j’abrite Némo et ses amis derrière ma vitre.",
  "Couronne": "Cercle doré sur la tête des reines ; en carton, je coiffe qui trouve la fève.",
  "Igloo": "Dôme de blocs blancs, j’abrite l’Inuit du blizzard ; dedans, il fait doux.",
  "Sablier": "Deux ventres de cristal : je laisse filer mes grains pour compter les minutes.",
  "Serre": "Palais de vitres, je garde les tomates au chaud ; mon effet réchauffe la Terre.",
  "Tirelire": "Petit goret rose au dos fendu, j’avale tes pièces ; me briser rend riche !",
  "Parasol": "Champignon rayé planté dans le sable, je t’offre un coin frais en été.",
  "Zoo": "On y voit des tigres derrière des grilles ; défense de nourrir les animaux !",
  "Allumette": "Tête rouge, je m’embrase d’un coup sec ; la fillette d’Andersen me vendait.",
  "Humain": "Bipède sans plumes, disait Platon ; je me crois roi de la Création.",
  "Héros": "Cape au vent, je sauve la veuve et l’orphelin, puis disparais sans un merci.",
  "Épée": "Lame à double tranchant, je dors au fourreau ; Excalibur est ma sœur célèbre.",
  "Brique": "Rouge et rectangulaire, je m’empile ; le troisième petit cochon m’a choisie.",
  "Maison": "On m’habite, on m’aime, on y rentre le soir poser ses clés : home sweet home !",
  "Chevalier": "Sans peur et sans reproche, je sers ma dame et siège à la Table ronde.",
  "Château": "Donjon, douves, créneaux : je défends la princesse… ou je m’élève en Espagne.",
  "Ville": "Klaxons, métro, néons : je ne dors jamais, surtout quand je m’appelle New York.",
  "Arche": "Noé m’a remplie d’animaux deux par deux, pendant quarante jours de pluie.",
  "Outil": "Prolongement de ta main, pince, scie ou tournevis, je dors dans la caisse.",
  "Hache": "Le bûcheron me lève et le chêne tremble ; on m’enterre pour faire la paix.",
  "Marteau": "Thor me lance, le clou me craint ; gare à qui se trouve entre moi et l’enclume !",
  "Lance": "Longue hampe à la pointe aiguë, je me brise contre l’écu dans les joutes.",
  "Arc": "Courbé puis tendu, je propulse la flèche ; Robin de Sherwood ne me quitte pas.",
  "Roue": "Je tourne rond depuis des millénaires ; inutile de me réinventer, dit-on.",
  "Charrette": "Tirée par un âne, je cahote vers le marché, chargée de foin et de choux.",
  "Bateau": "Coque, proue et poupe, je fends les flots ; plié en papier, je vogue en flaque.",
  "Voile": "Gonflée par la brise, je pousse le navire ; me mettre, c’est filer en douce.",
  "Agriculture": "Labourer, semer, récolter : depuis dix mille ans, je nourris les peuples.",
  "Champ": "Ma surface dorée ondule au vent d’été ; les coquelicots y piquent du rouge.",
  "Ferme": "Coq, grange et tracteur : dans celle à Mathurin, les canards font coin-coin.",
  "Farine": "Poudre blanche du boulanger, je fais des nuages dans la cuisine quand on pétrit.",
  "Pain": "Croûte dorée, mie moelleuse ; la baguette est ma forme la plus célèbre.",
  "Four": "Bouche chaude où lèvent les gâteaux ; Gretel y a poussé la sorcière.",
  "Poterie": "Mains mouillées sur le tour, tu façonnes bols et vases de terre cuite.",
  "Feu de camp": "Guimauves grillées et chansons : on se conte des histoires autour de moi.",
  "Cuisine": "Casseroles, fumets, tabliers ; un chef y mitonne, un rat y fait la ratatouille.",
  "Viande": "Saignante, à point ou bien cuite ? Le boucher me découpe en steaks.",
  "Lait": "Blanc et tiède, je te fais une moustache au petit-déjeuner et je déborde.",
  "Fromage": "Troué ou coulant, je sens parfois les pieds ; le Français m’adore avec du vin.",
  "Vin": "Rouge, blanc ou rosé, je vieillis en cave ; à Cana, l’eau devint moi.",
  "Bière": "Dorée sous mon col d’écume, je fais trinquer les chopes des tavernes.",
  "Miel": "Or liquide des butineuses, je colle aux doigts et j’adoucis ta tisane.",
  "Huile": "Je flotte toujours sur l’eau, je dore tes frites et fais chanter la poêle.",
  "Vêtement": "Je te couvre des épaules aux chevilles ; sans moi, tu serais tout nu !",
  "Écriture": "Des signes tracés pour que la parole survive au silence des siècles.",
  "Livre": "J’ai un dos mais pas de jambes, des pages mais pas de voix… ouvre-moi !",
  "Monnaie": "Ronde et sonnante, je passe de poche en poche ; pile ou face ?",
  "Commerce": "Acheter, vendre, troquer : je fais voyager les épices au bout du monde.",
  "Marché": "Étals colorés et voix qui crient leurs prix : on y vient le panier au bras.",
  "Route": "Ruban gris qui serpente entre les champs, je mène toujours quelque part.",
  "Pont": "Je tends le bras d’une rive à l’autre pour que tu passes au sec.",
  "Village": "Un clocher, quelques toits, une place où tout le monde se connaît.",
  "Mur": "J’ai des oreilles, dit-on, et je sépare les voisins sans jamais bouger.",
  "Tour": "Haute et fière, je guette l’horizon ; à Pise, je penche un peu.",
  "Temple": "Colonnes et encens : on y vient prier les immortels à pas feutrés.",
  "Pyramide": "Triangle géant posé sur le sable de Gizeh, je défie le ciel depuis toujours.",
  "Loi": "Nul n’est censé m’ignorer : je dis ce qui est permis et ce qui est défendu.",
  "Roi": "Couronne au front, sceptre en main, j’ai mon trône et toute ma cour.",
  "Armée": "Des milliers de pas qui frappent le sol au même rythme : en avant, marche !",
  "Guerre": "Canons, ruines et larmes : je dresse les peuples les uns contre les autres.",
  "Paix": "Une colombe, un rameau : je suis ce qui reste quand les canons se taisent.",
  "Religion": "Rites, prières et croyances : je relie la terre au ciel.",
  "Musique": "Sept notes me suffisent pour te faire pleurer ou danser.",
  "Art": "Je ne sers à rien, dit-on, et pourtant les musées me gardent comme un trésor.",
  "Peinture": "Pinceau trempé, toile blanche : je fais naître des couleurs là où rien n’était.",
  "Sculpture": "J’ôte tout ce qui n’est pas la statue, coup de ciseau après coup de ciseau.",
  "Théâtre": "Trois coups, le rideau se lève : sur les planches, on joue à être un autre.",
  "École": "Cartables, craie et récré : c’est ici que tu as appris à lire.",
  "Science": "Hypothèse, expérience, preuve : je doute de tout pour mieux comprendre.",
  "Médecine": "Stéthoscope au cou, je soigne les corps depuis Hippocrate.",
  "Port": "Quais, grues et mâts : les navires y rentrent pour se reposer.",
  "Puits": "Seau, poulie et margelle : je te remonte la fraîcheur du fond de la terre.",
  "Moulin": "Mes grands bras tournent dans la brise ; Don Quichotte m’a pris pour un géant.",
  "Forge": "Soufflet, enclume et étincelles : ici, l’acier rougeoyant se plie.",
  "Tente": "Toile, piquets et sardines : ma maison se plie dans ton sac à dos.",
  "Chasse": "Pister, guetter, viser : la traque du gibier au fond des bois.",
  "Pêche": "Assis au bord de l’étang, tu attends patiemment que le bouchon plonge.",
  "Élevage": "Bergers et étables : je nourris et fais grandir les troupeaux.",
  "Tisserand": "Navette en main, je croise les fils sur mon métier jour après jour.",
  "Forgeron": "Tablier de cuir et biceps d’acier, je frappe l’enclume du matin au soir.",
  "Philosophie": "Socrate savait qu’il ne savait rien ; moi, je questionne tout, même toi.",
  "Mathématiques": "Deux et deux font quatre, et pi ne finit jamais : bienvenue chez moi !",
  "Carte": "Je tiens le monde à plat ; suis mes lignes, le trésor est sous la croix.",
  "Boussole": "Mon aiguille frissonne toujours vers le nord, fidèle aux marins perdus.",
  "Calendrier": "Douze pages, trois cent soixante-cinq cases : je compte tes jours.",
  "Horloge": "Tic-tac, mes deux aiguilles se poursuivent sans jamais s’attraper.",
  "Bougie": "Souffle sur moi en faisant un vœu ; je pleure en fondant, petite flamme.",
  "Momie": "Enroulée de bandelettes, je dors dans mon sarcophage… ne me réveille pas !",
  "Pop-corn": "Grain doré qui éclate en nuage blanc, je croustille devant le grand écran.",
  "Caramel": "Ambré et collant, je file en nappe dorée sur ta crème brûlée.",
  "Gâteau": "Bougies plantées sur le dos, je suis la star de ton anniversaire.",
  "Soupe": "Fumante dans ton bol, je réchauffe l’hiver ; on me sert à la louche.",
  "Panier": "Osier tressé, je pends à ton bras pour la cueillette au verger.",
  "Cloche": "Ding, dang, dong ! Pendue là-haut, je chante les heures et les mariages.",
  "Feu d'artifice": "Bouquets de lumière qui éclatent dans la nuit du 14 Juillet : oh ! ah !",
  "Beurre": "Battue à la baratte, la crème devient moi : tartine-moi généreusement !",
  "Pâtes": "Spaghettis, coquillettes ou farfalles : l’Italie dans ton assiette, al dente.",
  "Crêpe": "Fine et dorée, je saute dans la poêle à la Chandeleur ; rattrape-moi !",
  "Frites": "Bâtonnets dorés et croustillants, je suis la fierté de la Belgique.",
  "Jus de fruit": "Une orange essorée, et me voilà prêt à réveiller ton petit-déjeuner.",
  "Crème glacée": "En cornet ou en pot, je fonds sur ta langue au soleil de juillet.",
  "Croissant": "Feuilleté en forme de lune, je sème mes miettes dans ton café crème.",
  "Sandwich": "Un comte joueur m’inventa pour manger sans quitter sa partie de cartes.",
  "Lit": "Oreiller, couette et matelas : je t’attends chaque soir pour tes rêves.",
  "Porte": "Toc toc ! Je m’ouvre aux amis et je claque au nez des importuns.",
  "Fenêtre": "Je suis l’œil de ta chambre ; ouvre-moi et l’air frais du matin entre.",
  "Clé": "Petite et dentelée, je tourne dans la serrure et libère les secrets.",
  "Parapluie": "Je m’ouvre quand le ciel pleure et me retourne au premier coup de vent.",
  "Fermier": "Debout avec le coq, je laboure, je sème et je trais avant l’aube.",
  "Pot de fleurs": "Sur le rebord de ta fenêtre, je berce un géranium dans mon ventre d’argile.",
  "Hôpital": "Brancards, blouses et sirènes : ici, on répare les corps cassés.",
  "Rails": "Deux sœurs parallèles qui filent sans jamais se toucher ; le train les suit.",
  "Guitare": "Six fils tendus sur un ventre creux : gratte-moi autour d’un feu de camp.",
  "Piano": "Quatre-vingt-huit touches noires et blanches ; Mozart me caressait des doigts.",
  "Tambour": "Frappe ma peau tendue et je gronde comme un cœur qui bat.",
  "Danse": "Valse, tango ou salsa : laisse tes pieds suivre le rythme !",
  "Ballon": "Rond et rebondissant, je file dans les buts sous les cris des tribunes.",
  "Ski": "Deux longues planches aux pieds, tu glisses sur la poudreuse en zigzag.",
  "Cerf-volant": "Au bout de mon fil, je danse dans la brise et fais lever les yeux des petits.",
  "Bonhomme de neige": "Une carotte pour nez, deux cailloux pour yeux, je fonds au printemps.",
  "Sushi": "Bouchée nippone roulée, je plonge dans la sauce soja au bout des baguettes.",
  "Hameçon": "Petit crochet pointu, je cache ma ruse sous un ver qui se tortille.",
  "Bouée": "Couronne gonflée autour de ta taille, je te garde à flot dans les vagues.",
  "Chaussure": "Cendrillon m’a perdue sur les marches du palais ; lace-moi bien, toi !",
  "Botte": "Haute jusqu’au genou, je fonce dans les flaques ; un chat célèbre en portait.",
  "Chaussette": "La machine à laver mange toujours ma jumelle ; je réchauffe tes orteils.",
  "Manteau": "Boutonne-moi jusqu’au col quand le givre mord tes joues.",
  "Maillot de bain": "Je sèche au soleil après le plongeon ; du sable dans mes plis, garanti !",
  "Blouse blanche": "Les docteurs m’enfilent au chevet des malades, immaculée comme la neige.",
  "Porte-monnaie": "Petit ventre à fermoir, je garde tes pièces au chaud dans ta poche.",
  "Boulanger": "Avant l’aube, je pétris la pâte de tes baguettes croustillantes.",
  "Cuisinier": "Sous ma toque blanche, je goûte, je sale et je crie « Service ! » aux fourneaux.",
  "Pompier": "Casque, sirène et grande échelle : je fonce vers les flammes que tu fuis.",
  "Médecin": "Dis « Aaah » ! Stéthoscope au cou, j’écris des ordonnances que nul ne sait lire.",
  "Maçon": "Truelle en main et fil à plomb, j’élève ta maison rang après rang.",
  "Pilote": "« Ici votre commandant de bord » : c’est moi, aux manettes, par-delà les nuages.",
  "Gratte-ciel": "Géant de vitres à cent étages, je chatouille le ventre des nues à Manhattan.",
  "Gare": "Quais, valises et annonces nasillardes : ici, on se dit adieu ou bienvenue.",
  "Église": "Nef, autel et bancs de bois : le dimanche, on y chante et on y prie.",
  "Ruine": "Pans éventrés, fenêtres vides : je suis ce qu’il reste quand tout s’effondre.",
  "Restaurant": "Nappe blanche, menu du jour, addition : ici, on dîne sans faire la vaisselle !",
  "Hôtel": "Réception, clé numérotée, petit savon : ici, on dort loin de chez soi.",
  "Stylo": "Ma bille roule sur la page ; on me mâchouille, on me perd, on me chipe.",
  "Cartable": "Sur ton dos à la rentrée, je pèse lourd de manuels, de trousses et de goûters.",
  "Journal": "Chaque matin je raconte le monde ; le lendemain, j’emballe le poisson.",
  "Alphabet": "De A à Z, vingt-six petites briques pour bâtir tous les mots.",
  "Dictionnaire": "Pavé savant, je range tous les mots de A à Z et j’explique chacun.",
  "Astronaute": "En scaphandre, je flotte en apesanteur et je vois la Terre toute ronde.",
  "Tarte": "Pâte brisée en cercle, garnie d’abricots ; Tatin m’a servie à l’envers !",
  "Biscuit": "Petit, sec et croquant, je fais trempette dans ton lait au goûter.",
  "Beignet": "Rond et doré, je sors de la friture tout poudré, la confiture au cœur.",
  "Sorbet": "Boule fraîche au citron, sans lait ni crème : je fonds sur ta langue en été.",
  "Limonade": "Pétillante et citronnée, mes bulles te chatouillent le nez par temps chaud.",
  "Cocktail": "Petit parasol et paille colorée : on me secoue au shaker avant de trinquer.",
  "Rhum": "Boisson des pirates des Caraïbes : yo-ho-ho, et une bouteille de moi !",
  "Bibliothèque": "Chut ! Ici dorment mille histoires sur des rayons, prêtes à être empruntées.",
  "Miroir": "Dis-moi, qui est la plus belle ? Je te renvoie ton reflet, mais à l’envers.",
  "Lampe à huile": "Frotte-moi bien : un génie pourrait sortir de ma panse d’argile.",
  "Couteau": "J’ai une lame et un manche ; je tranche le pain et je beurre tes tartines.",
  "Ciseaux": "Deux lames qui se croisent : je bats la feuille, mais la pierre m’écrase.",
  "Ours en peluche": "Teddy pour les intimes, je veille sur ton oreiller et chasse les cauchemars.",
  "Cahier": "Spirale ou agrafes, grands carreaux : mes pages attendent tes dictées.",
  "Pelle": "Je creuse des trous au jardin et j’aide à bâtir des châteaux sur la plage.",
  "Chocolat": "Noir, au lait ou blanc, je fonds en tablette et fais craquer les gourmands.",
  "Cidre": "Doux ou brut, je pétille dans la bolée à côté des crêpes bretonnes.",
  "Parc": "Bancs, pelouses et pigeons : un coin de verdure où l’on promène le chien.",
  "Chocolat chaud": "Une tasse fumante et brune, une moustache de mousse : l’hiver devient doux.",
  "Confiture": "Fraise ou abricot, je mijote au chaudron puis je dors en pots sur l’étagère.",
  "Mayonnaise": "Jaune et onctueuse, je fais la paire avec les frites ; je tourne si tu rates.",
  "Fontaine": "Jette une pièce dans mon bassin et fais un vœu, comme à Trevi.",
  "Cimetière": "Allées de cyprès et chrysanthèmes : ici reposent ceux qui nous ont quittés.",
  "Crayon": "Plus on me taille, plus je raccourcis ; mais ma mine reste vive.",
  "Potier": "Mains mouillées sur le tour, je fais naître vases et bols d’une motte de terre.",
  "Bûcheron": "Chemise à carreaux, cognée à l’épaule, je fais tomber les géants des bois.",
  "Berger": "Houlette en main, je compte mon troupeau la nuit sous les étoiles.",
  "Pêcheur": "Patient au bord de l’étang, j’attends que ça morde ; ma prise grandit au récit.",
  "Gomme": "Je mange tes erreurs et laisse des miettes roses sur ta copie.",
  "Phare": "Sentinelle des côtes, je balaie la nuit pour que les navires évitent les récifs.",
  "Armure": "Je cliquette à chaque pas : une carapace de plaques pour le preux en tournoi.",
  "Douves": "Fossé noyé autour du donjon : traverse à la nage, assaillant, si tu l’oses !",
  "Pont-levis": "Je me relève au bout de mes chaînes quand l’ennemi approche du donjon.",
  "Blason": "Sur l’écu, je peins ta lignée en gueules, azur et sinople.",
  "Catapulte": "Mon bras se détend d’un coup et des rochers volent par-dessus les remparts.",
  "Fer à cheval": "Cloué sous un sabot, je porte bonheur pendu au-dessus de ta porte.",
  "Vitrail": "Quand le soleil me traverse, des saints colorés dansent sur les dalles.",
  "Troubadour": "Luth en bandoulière, je chante la belle dame de cour en cour.",
  "Carrosse": "Doré pour le bal de Cendrillon, je redeviens potiron au douzième coup.",
  "Pantoufle de verre": "Perdue sur les marches à minuit, je ne chausse qu’un seul petit pied.",
  "Bottes de sept lieues": "Chipées au géant par le Petit Poucet, je franchis les vallées d’une enjambée.",
  "Maison en pain d'épices": "Hansel et Gretel ont grignoté mes murs ; la sorcière, elle, attendait.",
  "Clou": "Petite tige pointue, je m’enfonce sous les coups et je tiens les planches.",
  "Poulie": "Ma gorge guide le câble ; avec moi, le seau remonte du puits sans peine.",
  "Cabane": "Perchée dans les branches, c’est ton QG secret : interdit aux grands !",
  "Menuisier": "Rabot, varlope et copeaux : je fais naître tables et portes à l’atelier.",
  "Papier peint": "En rouleaux à motifs, je tapisse le salon ; gare aux bulles !",
  "Mécanicien": "Mains noires de cambouis, je glisse sous ton auto pour la réparer.",
  "Gâteau d'anniversaire": "Souffle d’un coup toutes mes petites flammes et fais un vœu !",
  "Cadeau": "Ruban, nœud, emballage brillant : qu’y a-t-il dans la boîte ? Secoue-moi !",
  "Sapin de Noël": "Guirlandes et boules au salon, je garde les paquets à mes pieds jusqu’au 25.",
  "Traîneau": "Tiré par huskies ou rennes, je glisse sur mes patins à travers la toundra.",
  "Mariage": "Robe blanche, « oui » sous le voile et riz qui pleut : le plus beau jour !",
  "Ballon de baudruche": "Gonfle-moi fort, fais un nœud… mais gare à l’épingle : pan !",
  "Jeu": "Des règles, des dés, un gagnant : on rit, on triche un peu… à toi de lancer !",
  "Sport": "Courir, sauter, transpirer : un esprit sain dans un corps sain, dit-on.",
  "Jeux olympiques": "Cinq anneaux, une flamme : tous les quatre ans, le monde court après l’or.",
  "Médaille": "Ronde et pendue à un ruban, on me mord sur le podium pour la photo.",
  "Natation": "Crawl, brasse ou papillon : enfile ton bonnet et enchaîne les longueurs.",
  "Patin à glace": "Lame fine sous la bottine, je glisse en arabesques sur le lac gelé.",
  "Football": "Onze contre onze, sans les mains : tout le stade hurle quand le filet tremble !",
  "Échecs": "Sur soixante-quatre cases, fous et cavaliers protègent leur souverain. Mat !",
  "Grange": "Grand ventre de planches, j’abrite les bottes de paille et les chouettes.",
  "Épouvantail": "Bras en croix et chapeau troué, je monte la garde ; les corneilles rient.",
  "Potager": "Radis, carottes et courgettes poussent en rangs sages derrière la maison.",
  "Arrosoir": "Mon long bec verse une pluie douce sur les fleurs assoiffées.",
  "Moisson": "Faux et faucilles au soleil d’août : on rentre les épis dorés.",
  "Silex taillé": "Éclat après éclat, Cro-Magnon m’a donné un tranchant de rasoir.",
  "Chasseur-cueilleur": "Mammouth le matin, baies l’après-midi : je vis nomade, sans champ ni grenier.",
  "Menhir": "Obélix me porte sur son dos ; je me dresse, géant, dans les landes bretonnes.",
  "Dolmen": "Une grosse dalle posée sur deux piliers : une table de géant à Carnac.",
  "Épave": "Coque éventrée au fond des flots, je sers de logis aux poissons.",
  "Trésor": "Une croix sur le parchemin, un coffre plein de doublons : creuse ici !",
  "Salade": "Verte, on me retourne dans un bol ; niçoise, je porte thon et olives.",
  "Parfum": "Deux gouttes au creux du cou, et tu laisses un sillage envoûtant.",

  # Histoire
  "Préhistoire": "Je suis l’époque d’avant les mots écrits : silex taillés et bisons aux parois.",
  "Âge de pierre": "Silex taillé, biface au poing : l’époque la plus caillouteuse de notre histoire.",
  "Âge du bronze": "Le rouge épouse le blanc au creuset : l’alliage doré détrône enfin le silex.",
  "Âge du fer": "Les Celtes battent l’enclume : le gris qui rouille détrône l’alliage doré.",
  "Antiquité": "Toges, colonnes et amphores : l’époque où Rome et Athènes faisaient la loi.",
  "Égypte ancienne": "Au bord du Nil : des scribes, des chats sacrés et des dieux à tête de faucon.",
  "Pharaon": "Fils de Râ, coiffé du némès, j’attends l’éternité dans mon sarcophage doré.",
  "Grèce antique": "Homère y chantait Ulysse, Socrate y questionnait tout le monde sur l’agora.",
  "Empire romain": "Tous les chemins mènent chez moi ; César et ses légions en savent quelque chose.",
  "Moyen Âge": "Donjons, troubadours et cathédrales : mille ans entre l’Antiquité et Léonard.",
  "Renaissance": "Léonard peint la Joconde, Michel-Ange sculpte : l’Europe sort enfin de sa nuit.",
  "Grandes découvertes": "Colomb, Magellan, Vasco de Gama : à bord des caravelles, la Terre s’élargit !",
  "Explorateur": "Je rêve des taches blanches sur les mappemondes, et je pars les remplir.",
  "Révolution": "Le peuple se lève, les pavés volent et une Bastille tombe un 14 juillet.",
  "Démocratie": "Une voix, un bulletin, une urne : ici, c’est le peuple qui tient la barre.",
  "Révolution industrielle": "Cheminées qui fument, métiers mécaniques : au XIXᵉ siècle, le monde accélère.",
  "Ère atomique": "Depuis 1945, le plus infime grain de matière éclaire nos villes et nos peurs.",
  "Conquête spatiale": "Spoutnik, Gagarine, puis un petit pas dans la mer de la Tranquillité.",
  "Ère numérique": "Tout se compte en zéros et en uns ; tes photos de chat vivent dans un nuage.",
  "Civilisation": "Des lois, des cités, des rites : c’est quand les tribus deviennent un peuple.",
  "Empire": "Un seul souverain pour mille provinces : Napoléon rêvait d’en bâtir un immense.",
  "Archéologie": "Indiana Jones en a fait une aventure ; moi, je creuse surtout avec un pinceau.",
  "Musée": "Chut ! Vitrines, statues et squelettes de dinosaures : on regarde sans toucher.",
  "Chronique": "Jour après jour, le moine consigne les règnes et les batailles du royaume.",
  "Mythologie": "Zeus, Thor, Osiris et leurs folles querelles : les légendes sacrées des peuples.",
  "Pirate": "Jambe de bois, bandeau sur l’œil et drapeau à tête de mort : à l’abordage !",
  "Néolithique": "Fini la cueillette errante : on sème, on garde les chèvres, on polit le silex.",
  "Grotte ornée": "À Lascaux, des bisons galopent sur la roche depuis dix-sept mille ans.",

  # Technologie
  "Machine à vapeur": "Je souffle, je siffle et je pousse des pistons ; James Watt m’a perfectionnée.",
  "Moteur": "Je ronronne sous le capot ; sans moi, ta voiture ne serait qu’un fauteuil.",
  "Machine": "Rouages, leviers et engrenages : je travaille sans relâche et sans me plaindre.",
  "Usine": "Cheminées, sirène de huit heures, chaîne de montage : voici l’atelier géant.",
  "Locomotive": "Tchou-tchou ! Je tire les wagons en crachant mon panache noir.",
  "Train": "Wagons à la queue leu leu, je file de quai en quai ; attention au départ !",
  "Voiture": "Quatre pneus, un volant, une ceinture… et des bouchons le dimanche soir.",
  "Avion": "Je décolle d’une piste et je traverse les nuages ; bouclez vos ceintures !",
  "Fusée": "Trois, deux, un… je crache le tonnerre et je file vers les étoiles !",
  "Satellite": "Lune artificielle, je tourne sans fin là-haut et j’espionne la météo.",
  "Ampoule": "Edison m’a fait briller ; dans les BD, je m’allume quand tu as une idée !",
  "Batterie": "Je garde le jus en réserve ; quand je faiblis, ton téléphone s’éteint.",
  "Téléphone": "Allô ? Bell m’a inventé pour que ta voix voyage au bout d’un fil.",
  "Radio": "Je parle et je chante sans visage ; tourne mon bouton pour changer de station.",
  "Télévision": "Petite lucarne du salon, j’offre le journal de 20 heures et les dessins animés.",
  "Ordinateur": "Clavier, souris, écran : je calcule plus vite que toi, mais je ne sais rêver.",
  "Internet": "Le grand filet mondial où chacun se parle, s’informe… et regarde des chats.",
  "Robot": "Bip bip ! Serviteur de tôle, j’ai pour cousins R2-D2 et WALL-E.",
  "Intelligence artificielle": "Je réponds à tes questions et j’écris des poèmes sans avoir jamais eu d’enfance.",
  "Panneau solaire": "Je bronze sur les toits et je transforme chaque rayon en courant.",
  "Éolienne": "Grande fleur blanche à trois pales, je fais du courant quand la brise souffle.",
  "Barrage": "Je retiens un fleuve entier dans mes bras et je fais tourner des turbines.",
  "Centrale nucléaire": "Mes tours crachent de gros nuages blancs ; dedans, Homer Simpson somnole.",
  "Microscope": "Penche ton œil sur moi : une goutte d’étang devient un zoo grouillant.",
  "Télescope": "Galilée m’a pointé vers Jupiter et y a vu danser quatre petites lunes.",
  "Imprimerie": "Gutenberg m’a lancée : caractères mobiles, presse, et la Bible pour tous.",
  "Appareil photo": "Clic ! Souris, ne bouge plus : je fige l’instant pour toujours.",
  "Cinéma": "Les frères Lumière m’ont fait naître ; éteins, la séance commence !",
  "Vaccin": "Une petite piqûre aujourd’hui, et ton corps saura se défendre demain.",
  "Antibiotique": "Fleming m’a découvert par hasard dans une boîte moisie ; les germes me fuient.",
  "Laser": "Sabre des Jedi ou pointeur de prof, je suis un rayon parfaitement droit.",
  "Électroaimant": "Branche-moi et j’agrippe les vieilles voitures ; coupe le courant, je les lâche.",
  "Station spatiale": "Refuge flottant à 400 km d’altitude : on y dort sanglé et on y boit en bulles.",
  "Sous-marin": "Jaune chez les Beatles, je plonge sans bruit au plus profond des vagues.",
  "Bombe atomique": "Un éclair, puis un champignon géant : Hiroshima ne m’a jamais oubliée.",
  "Puce électronique": "Petit carré de sable savant, je cache des milliards de transistors.",
  "Réseau électrique": "Pylônes et câbles tendus : je porte le courant jusqu’à ta prise.",
  "Moulin à eau": "Le ruisseau me pousse, ma meule écrase le grain ; plic, ploc, tic-tac.",
  "Sauvegarde": "Clique sur la disquette avant de fermer, ou tout ton travail s’envole !",
  "Lunettes": "Je chevauche ton nez et je remets le monde au point.",
  "Vélo": "Deux pédales, une chaîne, une sonnette : dring ! Le Tour de France m’adore.",
  "Moto": "Casque sur la tête, je file sur deux roues en vrombissant.",
  "Parachute": "Saute, tire la poignée, et ma corolle de toile t’offre une descente douce.",
  "Grue": "Long bras d’acier au-dessus des chantiers, je soulève des tonnes sans broncher.",
  "Bateau à vapeur": "Ma grande roue à aubes brasse le Mississippi sous l’œil de Tom Sawyer.",
  "Téléphérique": "Cabine pendue à un câble, je hisse les skieurs vers les sommets.",
  "Smartphone": "Tu me consultes cent fois par jour ; je tiens en poche et je sais presque tout.",
  "Radiotélescope": "Grande oreille tournée vers le ciel, j’écoute murmurer le cosmos…",
  "GPS": "« Dans 200 mètres, tournez à droite. » Grâce à moi, tu ne te perds plus.",
  "Feu tricolore": "Rouge, tu t’arrêtes ; vert, tu passes ; orange, tu hésites au carrefour.",
  "Tracteur": "Gros pneus crantés, je laboure les terres et ralentis les routes de campagne.",
  "Lampadaire": "Sentinelle des trottoirs, je m’allume au crépuscule pour les promeneurs.",
  "Montgolfière": "En 1783, un mouton, un canard et un coq ont voyagé sous ma grande bulle.",
  "Moissonneuse-batteuse": "Monstre rouge des étés, je fauche les épis et recrache la paille en bottes.",
  "Thermomètre": "Sous la langue ou sous le bras, je dis si tu as de la fièvre.",
  "Périscope": "Tube coudé qui pointe hors des vagues, je laisse l’équipage épier la surface.",
  "Paratonnerre": "Franklin m’a planté sur les toits pour attraper la foudre et la mener au sol.",

  # Légendes
  "Sphinx": "Sur la route de Thèbes, je pose ma devinette ; réponds mal et je te dévore.",
  "Magie": "Abracadabra ! Un lapin sort du chapeau, et nul ne sait jamais comment…",
  "Esprit": "Je pense, donc je suis : Descartes m’a logé quelque part sous ton crâne.",
  "Mana": "Jauge bleue des sorciers, je fonds à chaque sort et reviens si tu patientes.",
  "Orbe": "Boule lisse où la voyante lit ton avenir… ou que le roi tient dans sa main.",
  "Baguette": "Chez Ollivander, je choisis le sorcier ; chez le boulanger, je croustille.",
  "Pouvoir": "Il grise les rois ; absolu, il corrompt absolument, disait Lord Acton.",
  "Anneau": "Cercle d’éternité glissé au doigt, je dis « oui » sans ouvrir la bouche.",
  "Anneau de Pouvoir": "Un pour les gouverner tous ; Gollum m’appelait « mon précieux ».",
  "Feu Magique": "Flamme violette, je danse sans bûche et n’obéis qu’à l’enchanteur.",
  "Potion": "Obélix est tombé dedans quand il était petit ; Astérix n’en boit qu’une gorgée.",
  "Élixir": "Une gorgée dorée, et les rides s’effacent : les rois ont tout donné pour moi.",
  "Golem": "Glaise animée à Prague par un mot sacré au front ; efface-le et je m’écroule.",
  "Licorne": "Une spirale nacrée au front, je ne me laisse approcher que par les cœurs purs.",
  "Sorcier": "Chapeau pointu, barbe d’argent : Merlin et Gandalf sont de ma confrérie.",
  "Dragon": "Couché sur mon trésor, je crache des flammes ; saint Georges m’a terrassé.",
  "Phénix": "Je m’embrase quand je vieillis, puis je ressurgis, tout neuf, de mes braises.",
  "Hydre": "Coupe-moi une tête, deux repoussent ; Hercule a dû brûler chaque cou.",
  "Olympe": "Zeus y trône parmi les siens, au-dessus de la Grèce, entre nectar et ambroisie.",
  "Fantôme": "Drap blanc, chaînes qui grincent : je traverse les murs pour te faire bouh !",
  "Vampire": "Dracula est mon nom le plus célèbre ; l’ail et l’aube me font fuir.",
  "Loup-garou": "Quand l’astre est plein, mes poils poussent et je hurle ; l’argent seul me tue.",
  "Sirène": "Mon chant attire les marins vers les récifs ; Ulysse s’est fait attacher au mât.",
  "Géant": "Jack a grimpé sur un haricot pour piller mon château, tout là-haut.",
  "Fée": "Marraine de Cendrillon, d’un geste j’ai changé une citrouille en carrosse doré.",
  "Mythe": "Récit d’avant l’écriture, je raconte dieux et héros pour expliquer le monde.",
  "Dieu": "On me prie à genoux et l’on m’élève des temples ; je suis partout, dit-on.",
  "Démon": "Cornes, queue fourchue, pacte signé en lettres rouges : je veux ton âme.",
  "Ange": "Auréole sur la tête, je veille sur toi, perché sur ton épaule droite.",
  "Alchimie": "Changer le vil plomb en trésor doré : Nicolas Flamel y a consacré sa vie.",
  "Pierre philosophale": "Graal de Flamel et titre du premier Harry Potter : j’offre l’immortalité.",
  "Zombie": "Bras tendus, pas traînant, je ne réclame qu’une chose : des cerveaux !",
  "Kraken": "Des profondeurs nordiques, mes tentacules colossaux broient les navires.",
  "Centaure": "Torse d’homme sur corps d’étalon, Chiron fut le plus sage d’entre nous.",
  "Grimoire": "Tu me tiens en ce moment même : mes pages cachent sorts et formules.",
  "Génie": "Frotte mon logis de cuivre, je jaillis et t’accorde trois vœux.",
  "Ogre": "Le Petit Poucet m’a chipé mes bottes de sept lieues ; Shrek est mon cousin vert.",
  "Chat botté": "Matou rusé à chapeau à plume, j’ai fait de mon maître le marquis de Carabas.",
  "Père Noël": "Barbe blanche, habit rouge, je descends par la cheminée le 24 décembre.",
  "Monstre de Frankenstein": "Cousu de morceaux, réveillé par la foudre, on me donne le nom de mon créateur.",
  "Robin des Bois": "Je vole aux riches pour donner aux pauvres, caché à Sherwood en collant vert.",
  "Ailes d'Icare": "Dédale nous a collées sur son fils ; trop près de l’astre, nous avons fondu.",
  "Cheval de Troie": "Cadeau géant laissé sur la plage, j’avais le ventre plein de soldats grecs.",
  "Boîte de Pandore": "Ouvre-moi et tous les maux s’échappent ; au fond ne reste que l’espérance.",
  "Griffon": "Tête de rapace, corps de fauve : Gryffondor m’a emprunté une part de son nom.",
}
